/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.13
 * Generated at: 2025-12-05 01:30:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.pages;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.*;
import webservices.*;

public final class altaRegistro_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(7);
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("webservices");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

  String ctx = request.getContextPath();
  DtDetalleEdicion ed = (DtDetalleEdicion) request.getAttribute("edicion");
  @SuppressWarnings("unchecked")
  Set<DtTipoRegistro> tiposRegistro = (Set<DtTipoRegistro>) request.getAttribute("tiposRegistro");

  String error   = (String) request.getAttribute("error");
  String mensaje = (String) request.getAttribute("mensaje");

  String edicionStr = request.getParameter("edicion");
  if (edicionStr == null || edicionStr.isBlank()) {
      Object eStr = request.getAttribute("edicionStr");
      edicionStr = (eStr == null ? (ed != null ? ed.getNombre() : "") : String.valueOf(eStr));
  }

  String tipoRegistroSel = String.valueOf(request.getAttribute("tipoRegistroSel"));
  if (tipoRegistroSel == null || "null".equals(tipoRegistroSel)) tipoRegistroSel = "";

  String formaRegistroSel = String.valueOf(request.getAttribute("formaRegistroSel"));
  if (formaRegistroSel == null || "null".equals(formaRegistroSel)) formaRegistroSel = "general";

  String codigoPatVal = String.valueOf(request.getAttribute("codigoPatrocinioVal"));
  if (codigoPatVal == null || "null".equals(codigoPatVal)) codigoPatVal = "";

  String imagenEdicion = (String) request.getAttribute("imagenEdicion");
  if (imagenEdicion == null || imagenEdicion.isBlank()) imagenEdicion = "uploads/ediciones/default.jpg";

  String nombreEvento = (String) request.getAttribute("nombreEvento");
  if (nombreEvento == null) nombreEvento = "";

  String imagenEvento = (String) request.getAttribute("imagenEvento");
  if (imagenEvento == null || imagenEvento.isBlank()) imagenEvento = "uploads/eventos/default.jpg";

  Boolean yaRegistrado = (Boolean) request.getAttribute("yaRegistrado");
  if (yaRegistrado == null) yaRegistrado = false;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html lang=\"es\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\" />\r\n");
      out.write("<meta http-equiv=\"x-ua-compatible\" content=\"ie=edge\" />\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />\r\n");
      out.write("<title>Registro a Edición — Eventos.uy</title>\r\n");
      out.write("\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/boxicons@latest/css/boxicons.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Titillium+Web:wght@300;400;600&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print( ctx );
      out.write("/assets/css/ConsultaEvento.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print( ctx );
      out.write("/assets/css/styles.css\">\r\n");
      out.write("<style>\r\n");
      out.write(":root { --bg:#f4f6f8; --surface:#fff; --text:#1f2937; --muted:#6b7280; --border:#e6e8eb; --accent:#6d5dfc; --accent-weak:#edeaff; --radius:8px; --shadow:0 6px 18px rgba(15,23,42,.06); }\r\n");
      out.write("body { font-family: \"Titillium Web\", system-ui, -apple-system, \"Segoe UI\", Roboto, Arial, sans-serif; background:var(--bg); color:var(--text); margin:0;}\r\n");
      out.write("main.contUser { padding:18px; }\r\n");
      out.write(".container-xl { max-width:980px; }\r\n");
      out.write(".card { border:1px solid var(--border); border-radius:var(--radius); box-shadow:var(--shadow); }\r\n");
      out.write(".form-label { font-weight:600; }\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body id=\"body-pd\">\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/templates/header.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("<main class=\"contUser\">\r\n");
      out.write("  <div class=\"container-xl\">\r\n");
      out.write("\r\n");
      out.write("    <section class=\"card mb-3\">\r\n");
      out.write("      <div class=\"card-body d-flex align-items-center gap-3\">\r\n");
      out.write("      ");
 String back =  ed != null ? "detalleEdicion?nombre=" + ed.getNombre() : "HomeServlet"; 
      out.write("\r\n");
      out.write("        <a href=\"");
      out.print( back  );
      out.write("\" class=\"btn btn-light d-flex align-items-center justify-content-center p-2\"\r\n");
      out.write("           style=\"width:40px; height:40px; border-radius:50%;\">\r\n");
      out.write("          <i class='bx bx-chevron-left fs-4'></i>\r\n");
      out.write("        </a>\r\n");
      out.write("        <i class=\"bx bx-user-plus fs-3\"></i>\r\n");
      out.write("        <h2 class=\"mb-0 fw-bold\">Registro a Edición</h2>\r\n");
      out.write("      </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    ");
 if (error != null) { 
      out.write("\r\n");
      out.write("      <div class=\"alert alert-danger\">");
      out.print( error );
      out.write("</div>\r\n");
      out.write("    ");
 } 
      out.write("\r\n");
      out.write("    ");
 if (mensaje != null) { 
      out.write("\r\n");
      out.write("      <div class=\"alert alert-success\">");
      out.print( mensaje );
      out.write("</div>\r\n");
      out.write("    ");
 } 
      out.write("\r\n");
      out.write("    ");
 if (yaRegistrado) { 
      out.write("\r\n");
      out.write("      <div class=\"alert alert-warning\">Ya estás registrado en esta edición.</div>\r\n");
      out.write("    ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <section class=\"card mb-3\">\r\n");
      out.write("      <div class=\"card-body\">\r\n");
      out.write("        <form id=\"registroEdicionForm\" method=\"post\" action=\"");
      out.print( ctx );
      out.write("/altaRegistro\">\r\n");
      out.write("          <input type=\"hidden\" name=\"edicion\" value=\"");
      out.print( edicionStr );
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("          <!-- Edición + imagen -->\r\n");
      out.write("          <div class=\"mb-3 d-flex flex-column align-items-center justify-content-center\">\r\n");
      out.write("            <label class=\"form-label\">\r\n");
      out.write("              ");
      out.print( (ed != null ? ed.getNombre() : edicionStr) );
      out.write("\r\n");
      out.write("              ");
 if (nombreEvento != null && !nombreEvento.isBlank()) { 
      out.write("\r\n");
      out.write("                — <span class=\"text-muted\">");
      out.print( nombreEvento );
      out.write("</span>\r\n");
      out.write("              ");
 } 
      out.write("\r\n");
      out.write("            </label>\r\n");
      out.write("            <img src=\"");
      out.print( imagenEdicion );
      out.write("\" alt=\"Imagen Edición\"\r\n");
      out.write("                 class=\"img-fluid rounded\"\r\n");
      out.write("                 style=\"width:120px; height:120px; object-fit:cover;\">\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <!-- Tipo de registro -->\r\n");
      out.write("          <div class=\"mb-3\">\r\n");
      out.write("            <label for=\"tipoRegistroSelect\" class=\"form-label\">Tipo de registro</label>\r\n");
      out.write("            <select class=\"form-select\" id=\"tipoRegistroSelect\" name=\"tipoRegistro\" required>\r\n");
      out.write("              <option value=\"\">-- Seleccione un tipo de registro --</option>\r\n");
      out.write("              ");
 if (tiposRegistro != null) {
                   for (DtTipoRegistro tr : tiposRegistro) {
                      String nombreTr = "";
                      float  costoTr  = 0f;
                      try { nombreTr = (String) tr.getClass().getMethod("getNombre").invoke(tr); } catch (java.lang.Exception ignore) {}
                      try { Object c = tr.getClass().getMethod("getCosto").invoke(tr);
                            if (c instanceof Float f) costoTr = f;
                            if (c instanceof Double d) costoTr = d.floatValue();
                      } catch (java.lang.Exception ignore) {}
                      boolean sel = nombreTr.equals(tipoRegistroSel);
              
      out.write("\r\n");
      out.write("                <option value=\"");
      out.print( nombreTr );
      out.write('"');
      out.write(' ');
      out.print( sel ? "selected" : "" );
      out.write(">\r\n");
      out.write("                  ");
      out.print( nombreTr );
      out.write(' ');
 if (costoTr > 0) { 
      out.write(" — $");
      out.print( costoTr );
      out.write(' ');
 } 
      out.write("\r\n");
      out.write("                </option>\r\n");
      out.write("              ");
 }} 
      out.write("\r\n");
      out.write("            </select>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <!-- Forma de registro -->\r\n");
      out.write("          <div class=\"mb-3\">\r\n");
      out.write("            <label class=\"form-label\">Forma de registro</label>\r\n");
      out.write("            <div class=\"form-check\">\r\n");
      out.write("              <input class=\"form-check-input\" type=\"radio\"\r\n");
      out.write("                     name=\"formaRegistro\" id=\"formaGeneral\" value=\"general\"\r\n");
      out.write("                     ");
      out.print( ("patrocinio".equalsIgnoreCase(formaRegistroSel) ? "" : "checked") );
      out.write(">\r\n");
      out.write("              <label class=\"form-check-label\" for=\"formaGeneral\">General</label>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"form-check\">\r\n");
      out.write("              <input class=\"form-check-input\" type=\"radio\"\r\n");
      out.write("                     name=\"formaRegistro\" id=\"formaPatrocinio\" value=\"patrocinio\"\r\n");
      out.write("                     ");
      out.print( ("patrocinio".equalsIgnoreCase(formaRegistroSel) ? "checked" : "") );
      out.write(">\r\n");
      out.write("              <label class=\"form-check-label\" for=\"formaPatrocinio\">Usando código de patrocinio</label>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <!-- Código de patrocinio -->\r\n");
      out.write("          <div class=\"mb-3\" id=\"codigoPatrocinioDiv\"\r\n");
      out.write("               style=\"display: ");
      out.print( ("patrocinio".equalsIgnoreCase(formaRegistroSel) ? "block" : "none") );
      out.write(";\">\r\n");
      out.write("            <label for=\"codigoPatrocinio\" class=\"form-label\">Código de patrocinio</label>\r\n");
      out.write("            <input type=\"text\" class=\"form-control\" id=\"codigoPatrocinio\"\r\n");
      out.write("                   name=\"codigoPatrocinio\" placeholder=\"Ingrese el código\"\r\n");
      out.write("                   value=\"");
      out.print( codigoPatVal );
      out.write("\">\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <div class=\"d-flex gap-2\">\r\n");
      out.write("            <button type=\"submit\" class=\"btn btn-primary\" ");
      out.print( yaRegistrado ? "disabled" : "" );
      out.write(">\r\n");
      out.write("              Registrar\r\n");
      out.write("            </button>\r\n");
      out.write("            <a href=\"");
      out.print( back  );
      out.write("\" class=\"btn btn-secondary\">Cancelar</a>\r\n");
      out.write("          </div>\r\n");
      out.write("        </form>\r\n");
      out.write("      </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("  </div>\r\n");
      out.write("</main>\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("  // Toggle campo patrocinio\r\n");
      out.write("  document.querySelectorAll('input[name=\"formaRegistro\"]').forEach(el => {\r\n");
      out.write("    el.addEventListener('change', function() {\r\n");
      out.write("      document.getElementById('codigoPatrocinioDiv').style.display =\r\n");
      out.write("        this.value === 'patrocinio' ? 'block' : 'none';\r\n");
      out.write("    });\r\n");
      out.write("  });\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
