/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.13
 * Generated at: 2025-12-05 01:30:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.pages;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import webservices.*;

public final class detalleRegistro_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("webservices");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

  String ctx = request.getContextPath();
  DtRegistro reg = (DtRegistro) request.getAttribute("registro");
  if (reg == null) { 
      out.write("\r\n");
      out.write("  <h2>No hay datos de registro para mostrar.</h2>\r\n");
  return; }

  String imgUsuario  = (String) request.getAttribute("imagenUsuario");
  String imgEdicion  = (String) request.getAttribute("imagenEdicion");
  if (imgUsuario == null || imgUsuario.isBlank()) imgUsuario = "uploads/usuarios/default.jpg";
  if (imgEdicion == null || imgEdicion.isBlank()) imgEdicion = "uploads/ediciones/default.jpg";

  String nickUsuario   = (String) request.getAttribute("usuario");
  String nombreEdicion = reg.getNombreEdicion();
  String tipoReg       = reg.getTipoRegistro();
  boolean asistencia   = reg.isAsistencia();

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"es\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, viewport-fit=cover\">\r\n");
      out.write("<title>Detalle de Registro - Eventos.uy</title>\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print( request.getContextPath() );
      out.write("/assets/css/styles.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print( request.getContextPath() );
      out.write("/assets/css/detalleregistro.css\">\r\n");
      out.write("<link rel=\"icon\" type=\"image/x-icon\" href=\"");
      out.print( request.getContextPath() );
      out.write("/assets/icons/Logo.png\">\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("  body { font-size: 1.05rem; } /* sube todo un poco */\r\n");
      out.write("  .dr-title { font-size: 2rem; font-weight: 800; letter-spacing: .2px; } /* grande en mobile */\r\n");
      out.write("  .dr-muted { color: #6c757d; } /* similar a .text-muted, pero controlable */\r\n");
      out.write("\r\n");
      out.write("  .dr-list .list-group-item {\r\n");
      out.write("    padding: 1rem 1.1rem;\r\n");
      out.write("    font-size: 1.15rem;   /* texto grande en ítems */\r\n");
      out.write("    line-height: 1.25;\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  .badge-xl {\r\n");
      out.write("    font-size: 1.15rem;\r\n");
      out.write("    padding: .65rem 1rem;\r\n");
      out.write("    border-radius: .75rem;\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  .btn-block { width: 100%; }\r\n");
      out.write("\r\n");
      out.write("  .dr-avatars img {\r\n");
      out.write("    width: 150px; height: 150px; object-fit: cover;\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  .detalle-registro-card { border-radius: 1rem; }\r\n");
      out.write("  .detalle-registro-card .card-body { padding: 1.25rem; }\r\n");
      out.write("\r\n");
      out.write("  @media (min-width: 768px) {\r\n");
      out.write("    body { font-size: 1.05rem; }          /* mantenemos tamaño */\r\n");
      out.write("    .dr-title { font-size: 2.25rem; }     /* un toque más grande en md+ */\r\n");
      out.write("    .dr-avatars img { width: 170px; height: 170px; }\r\n");
      out.write("    .detalle-registro-card .card-body { padding: 2rem; }\r\n");
      out.write("  }\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("  ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/templates/header.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <div class=\"container d-flex flex-column align-items-stretch justify-content-center py-4\">\r\n");
      out.write("    <div class=\"card shadow detalle-registro-card mx-auto\" style=\"max-width: 820px;\">\r\n");
      out.write("      <div class=\"card-body\">\r\n");
      out.write("        <div class=\"dr-avatars row g-3 align-items-center justify-content-center mb-3 mb-md-4\">\r\n");
      out.write("          <div class=\"col-12 col-md-auto d-flex justify-content-center\">\r\n");
      out.write("            <img src=\"");
      out.print( imgUsuario );
      out.write("\" alt=\"Foto Usuario\"\r\n");
      out.write("                 class=\"img-fluid rounded-circle shadow-sm\">\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-12 col-md-auto d-flex justify-content-center\">\r\n");
      out.write("            <img src=\"");
      out.print( imgEdicion );
      out.write("\" alt=\"Foto Edición\"\r\n");
      out.write("                 class=\"img-fluid rounded shadow-sm\">\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"info-evento text-center\"\r\n");
      out.write("             data-usuario=\"");
      out.print( nickUsuario );
      out.write("\"\r\n");
      out.write("             data-edicion=\"");
      out.print( (nombreEdicion == null ? "" : nombreEdicion) );
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("          <h1 class=\"dr-title mb-3\">Detalle de Registro</h1>\r\n");
      out.write("\r\n");
      out.write("          <!-- Datos -->\r\n");
      out.write("          <ul class=\"list-group dr-list text-start mx-auto mb-3\" style=\"max-width: 640px;\">\r\n");
      out.write("            <li class=\"list-group-item d-flex justify-content-between align-items-center\">\r\n");
      out.write("              <span class=\"dr-muted\">Usuario</span>\r\n");
      out.write("              <strong class=\"ms-3\">");
      out.print( nickUsuario );
      out.write("</strong>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"list-group-item d-flex justify-content-between align-items-center\">\r\n");
      out.write("              <span class=\"dr-muted\">Edición</span>\r\n");
      out.write("              <strong class=\"ms-3\">");
      out.print( (nombreEdicion == null ? "" : nombreEdicion) );
      out.write("</strong>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"list-group-item d-flex justify-content-between align-items-center\">\r\n");
      out.write("              <span class=\"dr-muted\">Tipo de registro</span>\r\n");
      out.write("              <strong class=\"ms-3\">");
      out.print( (nombreEdicion == null ? "" : tipoReg) );
      out.write("</strong>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"list-group-item d-flex justify-content-between align-items-center\">\r\n");
      out.write("              <span class=\"dr-muted\">Fecha de registro</span>\r\n");
      out.write("              <strong class=\"ms-3\">");
      out.print( reg.getFechaRegistro() );
      out.write("</strong>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"list-group-item d-flex justify-content-between align-items-center\">\r\n");
      out.write("              <span class=\"dr-muted\">Costo</span>\r\n");
      out.write("              <strong class=\"ms-3\">$");
      out.print( reg.getCosto() );
      out.write("</strong>\r\n");
      out.write("            </li>\r\n");
      out.write("          </ul>\r\n");
      out.write("\r\n");
      out.write("          <!-- botncito para confirmra la asistencia -->\r\n");
      out.write("          <div class=\"mt-2\">\r\n");
      out.write("            <div class=\"d-flex flex-column flex-sm-row align-items-center justify-content-center gap-3\">\r\n");
      out.write("\r\n");
      out.write("              <div class=\"w-100 w-sm-auto\">\r\n");
      out.write("				  ");
 if (asistencia) { 
      out.write("\r\n");
      out.write("				    <a class=\"btn btn-outline-primary btn-lg btn-block\"\r\n");
      out.write("				       id=\"btnDescargarAsistencia\"\r\n");
      out.write("				       href=\"");
      out.print( ctx );
      out.write("/descargar-asistencia?usuario=");
      out.print( nickUsuario );
      out.write("&edicion=");
      out.print( nombreEdicion );
      out.write("\"\r\n");
      out.write("				       target=\"_blank\" rel=\"noopener\">\r\n");
      out.write("				      Descargar asistencia\r\n");
      out.write("				    </a>\r\n");
      out.write("				  ");
 } 
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("  <script>\r\n");
      out.write("(function(){\r\n");
      out.write("  const container = document.querySelector('.info-evento');\r\n");
      out.write("  const usuario = container?.dataset?.usuario || '';\r\n");
      out.write("  const edicion = container?.dataset?.edicion || '';\r\n");
      out.write("\r\n");
      out.write("  const btnDownload = document.getElementById('btnDescargarAsistencia');\r\n");
      out.write("  const badge = document.getElementById('asistenciaEstado');\r\n");
      out.write("\r\n");
      out.write("  const btnOk   = document.getElementById('btnModalConfirmar');\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  if (btnOk) {\r\n");
      out.write("    btnOk.addEventListener('click', async () => {\r\n");
      out.write("      try {\r\n");
      out.write("        const body = new URLSearchParams({ usuario, edicion });\r\n");
      out.write("        const resp = await fetch('");
      out.print( ctx );
      out.write("/confirmar-asistencia', {\r\n");
      out.write("          method: 'POST',\r\n");
      out.write("          headers: { 'Content-Type': 'application/x-www-form-urlencoded;charset=UTF-8' },\r\n");
      out.write("          body\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        const data = await resp.json();\r\n");
      out.write("        if (!resp.ok || !data.ok) throw new Error(data.error || 'Error desconocido');\r\n");
      out.write("\r\n");
      out.write("        if (badge) {\r\n");
      out.write("          badge.textContent = 'Confirmada';\r\n");
      out.write("          badge.className = 'badge badge-xl bg-success';\r\n");
      out.write("        }\r\n");
      out.write("        if (modal) modal.hide();\r\n");
      out.write("\r\n");
      out.write("        if (btnConfirm) {\r\n");
      out.write("        	  const parent = btnConfirm.parentElement;\r\n");
      out.write("        	  const a = document.createElement('a');\r\n");
      out.write("        	  a.id = 'btnDescargarAsistencia';\r\n");
      out.write("        	  a.className = 'btn btn-outline-primary btn-lg btn-block';\r\n");
      out.write("        	  a.textContent = 'Descargar asistencia';\r\n");
      out.write("        	  a.href = '");
      out.print( ctx );
      out.write("/descargar-asistencia?usuario=' + encodeURIComponent(usuario) +\r\n");
      out.write("        	           '&edicion=' + encodeURIComponent(edicion);\r\n");
      out.write("        	  a.target = '_blank';\r\n");
      out.write("        	  a.rel = 'noopener';\r\n");
      out.write("        	  parent.replaceChild(a, btnConfirm);\r\n");
      out.write("        	}\r\n");
      out.write("\r\n");
      out.write("      } catch (e) {\r\n");
      out.write("        alert('No se pudo confirmar la asistencia: ' + (e.message || e));\r\n");
      out.write("      }\r\n");
      out.write("    });\r\n");
      out.write("  }\r\n");
      out.write("})();\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
