/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.13
 * Generated at: 2025-12-04 21:02:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.pages;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import webservices.DataUsuario;
import webservices.DtOrganizador;
import webservices.DtAsistente;
import webservices.TipoUsuario;
import java.time.LocalDate;

public final class modificarDatos_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(7);
    _jspx_imports_classes.add("webservices.TipoUsuario");
    _jspx_imports_classes.add("webservices.DataUsuario");
    _jspx_imports_classes.add("java.time.LocalDate");
    _jspx_imports_classes.add("webservices.DtAsistente");
    _jspx_imports_classes.add("webservices.DtOrganizador");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

  String ctx = request.getContextPath();

  DataUsuario du = (DataUsuario) request.getAttribute("usuario");

  if (du == null) {
      String nickParam = request.getParameter("usuario");
      if (nickParam == null || nickParam.isBlank()) {
          response.sendRedirect(ctx + "/listarUsuarios?action=listar");
          return;
      } else {
          request.setAttribute("error", "No se pudo cargar el usuario solicitado.");
      }
  }

  String error   = (String) request.getAttribute("error");
  String mensaje = (String) request.getAttribute("mensaje");

  String nombreAttr      = (String) request.getAttribute("nombre");
  String apellidoAttr    = (String) request.getAttribute("apellido");
  String fechaNacAttr    = (String) request.getAttribute("fechaNac");
  String descripcionAttr = (String) request.getAttribute("descripcion");
  String webAttr         = (String) request.getAttribute("web");

  String nick  = (du != null ? du.getNickname() : "");
  String email = (du != null ? du.getEmail()    : "");

  String nombreVal = "";
  String apellidoVal = "";
  String fechaNacVal = "";
  String descripcionVal = "";
  String webVal = "";

  if (du != null && du.getTipo() == TipoUsuario.ASISTENTE) {
	    DtAsistente as = (DtAsistente) request.getAttribute("detalleUsuario");
	    nombreVal   = (nombreAttr != null) ? nombreAttr : (as != null ? as.getNombre() : du.getNombre());
	    apellidoVal = (apellidoAttr != null) ? apellidoAttr : (as != null ? as.getApellido() : "");
	    if (fechaNacAttr != null) {
	        fechaNacVal = fechaNacAttr;
	    } else if (as != null && as.getFechaNacimiento() != null) {
	        fechaNacVal = as.getFechaNacimiento().toString();
	    }
	} else if (du != null && du.getTipo() == TipoUsuario.ORGANIZADOR) {
	    DtOrganizador org = (DtOrganizador) request.getAttribute("detalleUsuario");
	    nombreVal      = (nombreAttr != null)      ? nombreAttr      : (org != null ? org.getNombre()      : du.getNombre());
	    descripcionVal = (descripcionAttr != null) ? descripcionAttr : (org != null ? org.getDescripcion() : "");
	    webVal         = (webAttr != null)         ? webAttr         : (org != null ? org.getWeb()         : "");
	}

      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html lang=\"es\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\" />\r\n");
      out.write("<meta http-equiv=\"x-ua-compatible\" content=\"ie=edge\" />\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />\r\n");
      out.write("<title>Modificar Perfil — Eventos.uy</title>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print( ctx );
      out.write("/assets/css/styles.css\">\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/boxicons@latest/css/boxicons.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css2?family=Inter&display=swap\" />\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Titillium+Web:wght@300;400;600&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print( ctx );
      out.write("/assets/css/ConsultaEvento.css\">\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write(":root {\r\n");
      out.write("  --bg: #f4f6f8;\r\n");
      out.write("  --surface: #ffffff;\r\n");
      out.write("  --text: #1f2937;\r\n");
      out.write("  --muted: #6b7280;\r\n");
      out.write("  --border: #e6e8eb;\r\n");
      out.write("  --accent: #6d5dfc;\r\n");
      out.write("  --accent-weak: #edeaff;\r\n");
      out.write("  --radius: 8px;\r\n");
      out.write("  --shadow: 0 6px 18px rgba(15, 23, 42, .06);\r\n");
      out.write("}\r\n");
      out.write("body { background: var(--bg); color: var(--text); margin: 0; }\r\n");
      out.write("main.contUser { padding: 18px; }\r\n");
      out.write(".container-xl { max-width: 980px; }\r\n");
      out.write(".card { border: 1px solid var(--border); border-radius: var(--radius); box-shadow: var(--shadow); }\r\n");
      out.write(".form-label { font-weight: 600; }\r\n");
      out.write(".avatar-preview { width: 80px; height: 80px; border-radius: 50%; object-fit: cover; border: 2px solid var(--accent-weak); }\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body id=\"body-pd\">\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/templates/header.jsp", out, false);
      out.write("\r\n");
      out.write("<main class=\"contUser\">\r\n");
      out.write("  <div class=\"container-xl\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Header del formulario -->\r\n");
      out.write("    <section class=\"card mb-3\">\r\n");
      out.write("      <div class=\"card-body d-flex align-items-center gap-3\">\r\n");
      out.write("        <a href=\"");
      out.print( ctx );
      out.write("/perfil\" class=\"btn btn-light d-flex align-items-center justify-content-center p-2\" style=\"width:40px;height:40px;border-radius:50%;\">\r\n");
      out.write("          <i class='bx bx-chevron-left fs-4'></i>\r\n");
      out.write("        </a>\r\n");
      out.write("        <i class=\"bx bx-user fs-3\"></i>\r\n");
      out.write("        <h2 class=\"mb-0 fw-bold\">Modificar Perfil</h2>\r\n");
      out.write("      </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    ");
 if (error != null) { 
      out.write("\r\n");
      out.write("      <div class=\"alert alert-danger\">");
      out.print( error );
      out.write("</div>\r\n");
      out.write("    ");
 } 
      out.write("\r\n");
      out.write("    ");
 if (mensaje != null) { 
      out.write("\r\n");
      out.write("      <div class=\"alert alert-success\">");
      out.print( mensaje );
      out.write("</div>\r\n");
      out.write("    ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Formulario de edición -->\r\n");
      out.write("    <section class=\"card mb-3\">\r\n");
      out.write("      <div class=\"card-body\">\r\n");
      out.write("        <form id=\"modificarPerfilForm\" method=\"post\" action=\"");
      out.print( ctx );
      out.write("/modificarDatos\" enctype=\"multipart/form-data\">\r\n");
      out.write("		  <input type=\"hidden\" name=\"action\" value=\"modificarDatos\">\r\n");
      out.write("		  <input type=\"hidden\" name=\"usuario\" value=\"");
      out.print( nick );
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("          <div class=\"mb-3 text-center\">\r\n");
      out.write("			  <img id=\"avatarPreview\"\r\n");
      out.write("			       src=\"");
      out.print(request.getAttribute("imagenUsuario"));
      out.write("\"\r\n");
      out.write("			       alt=\"Avatar\" class=\"avatar-preview mb-2\">\r\n");
      out.write("			  <input class=\"form-control\" type=\"file\" id=\"avatarInput\" name=\"avatar\" accept=\"image/*\">\r\n");
      out.write("		  </div>\r\n");
      out.write("\r\n");
      out.write("          ");
 if (du != null && du.getTipo() == TipoUsuario.ASISTENTE) { 
      out.write("\r\n");
      out.write("            <!-- ASISTENTE -->\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("              <div class=\"col-md-6 mb-3\">\r\n");
      out.write("                <label for=\"nombre\" class=\"form-label\">Nombre</label>\r\n");
      out.write("                <input type=\"text\" class=\"form-control\" id=\"nombre\" name=\"nombre\" value=\"");
      out.print( (nombreVal==null?"":nombreVal) );
      out.write("\" required>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"col-md-6 mb-3\">\r\n");
      out.write("                <label for=\"apellido\" class=\"form-label\">Apellido</label>\r\n");
      out.write("                <input type=\"text\" class=\"form-control\" id=\"apellido\" name=\"apellido\" value=\"");
      out.print( (apellidoVal==null?"":apellidoVal) );
      out.write("\" required>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"mb-3\">\r\n");
      out.write("              <label for=\"fechaNac\" class=\"form-label\">Fecha de nacimiento</label>\r\n");
      out.write("              <input type=\"date\" class=\"form-control\" id=\"fechaNac\" name=\"fechaNac\" value=\"");
      out.print( (fechaNacVal==null?"":fechaNacVal) );
      out.write("\" required>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("          ");
 } else if (du != null && du.getTipo() == TipoUsuario.ORGANIZADOR) { 
      out.write("\r\n");
      out.write("            <!-- ORGANIZADOR -->\r\n");
      out.write("            <div class=\"mb-3\">\r\n");
      out.write("              <label for=\"nombre\" class=\"form-label\">Nombre</label>\r\n");
      out.write("              <input type=\"text\" class=\"form-control\" id=\"nombre\" name=\"nombre\" value=\"");
      out.print( (nombreVal==null?"":nombreVal) );
      out.write("\" required>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"mb-3\">\r\n");
      out.write("              <label for=\"descripcion\" class=\"form-label\">Descripción</label>\r\n");
      out.write("              <textarea class=\"form-control\" id=\"descripcion\" name=\"descripcion\" rows=\"3\" required>");
      out.print( (descripcionVal==null?"":descripcionVal) );
      out.write("</textarea>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"mb-3\">\r\n");
      out.write("              <label for=\"web\" class=\"form-label\">Sitio web</label>\r\n");
      out.write("              <input type=\"url\" class=\"form-control\" id=\"web\" name=\"web\" placeholder=\"https://\" value=\"");
      out.print( (webVal==null?"":webVal) );
      out.write("\">\r\n");
      out.write("            </div>\r\n");
      out.write("          ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("          <div class=\"mb-3\">\r\n");
      out.write("            <label class=\"form-label\">Nickname</label>\r\n");
      out.write("            <input type=\"text\" class=\"form-control\" value=\"");
      out.print( nick );
      out.write("\" disabled>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <div class=\"mb-3\">\r\n");
      out.write("            <label class=\"form-label\">Correo electrónico</label>\r\n");
      out.write("            <input type=\"email\" class=\"form-control\" value=\"");
      out.print( email );
      out.write("\" disabled>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <div class=\"d-flex gap-2\">\r\n");
      out.write("            <button type=\"submit\" class=\"btn btn-primary\">Guardar</button>\r\n");
      out.write("            <a href=\"");
      out.print( ctx );
      out.write("/\" class=\"btn btn-secondary\">Cancelar</a>\r\n");
      out.write("          </div>\r\n");
      out.write("        </form>\r\n");
      out.write("      </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("  </div>\r\n");
      out.write("</main>\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("  // Preview de avatar (solo visual)\r\n");
      out.write("  const avatarInput = document.getElementById('avatarInput');\r\n");
      out.write("  const avatarPreview = document.getElementById('avatarPreview');\r\n");
      out.write("  if (avatarInput) {\r\n");
      out.write("    avatarInput.addEventListener('change', (e) => {\r\n");
      out.write("      const file = e.target.files[0];\r\n");
      out.write("      if (file) avatarPreview.src = URL.createObjectURL(file);\r\n");
      out.write("    });\r\n");
      out.write("  }\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
