
package webservices;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebFault(name = "EventoFinalizadoExcepcion", targetNamespace = "http://webservices/")
public class EventoFinalizadoExcepcion_Exception
    extends java.lang.Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private EventoFinalizadoExcepcion faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public EventoFinalizadoExcepcion_Exception(String message, EventoFinalizadoExcepcion faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param cause
     * @param faultInfo
     * @param message
     */
    public EventoFinalizadoExcepcion_Exception(String message, EventoFinalizadoExcepcion faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: webservices.EventoFinalizadoExcepcion
     */
    public EventoFinalizadoExcepcion getFaultInfo() {
        return faultInfo;
    }

}
