
package webservices;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.FaultAction;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "publicadorUsuario", targetNamespace = "http://webservices/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PublicadorUsuario {


    /**
     * 
     * @param arg0
     * @return
     *     returns int
     * @throws UsuarioNoEncontrado_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices/publicadorUsuario/cantidadSeguidosRequest", output = "http://webservices/publicadorUsuario/cantidadSeguidosResponse", fault = {
        @FaultAction(className = UsuarioNoEncontrado_Exception.class, value = "http://webservices/publicadorUsuario/cantidadSeguidos/Fault/UsuarioNoEncontrado")
    })
    public int cantidadSeguidos(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0)
        throws UsuarioNoEncontrado_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns int
     * @throws UsuarioNoEncontrado_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices/publicadorUsuario/cantidadSeguidoresRequest", output = "http://webservices/publicadorUsuario/cantidadSeguidoresResponse", fault = {
        @FaultAction(className = UsuarioNoEncontrado_Exception.class, value = "http://webservices/publicadorUsuario/cantidadSeguidores/Fault/UsuarioNoEncontrado")
    })
    public int cantidadSeguidores(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0)
        throws UsuarioNoEncontrado_Exception
    ;

    /**
     * 
     * @return
     *     returns webservices.WrapperHashSet
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices/publicadorUsuario/listarUsuariosRequest", output = "http://webservices/publicadorUsuario/listarUsuariosResponse")
    public WrapperHashSet listarUsuarios();

    /**
     * 
     * @param arg0
     * @return
     *     returns webservices.DtAsistente
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices/publicadorUsuario/infoAsistenteRequest", output = "http://webservices/publicadorUsuario/infoAsistenteResponse")
    public DtAsistente infoAsistente(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns webservices.DataUsuario
     * @throws UsuarioNoEncontrado_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices/publicadorUsuario/infoUsuarioRequest", output = "http://webservices/publicadorUsuario/infoUsuarioResponse", fault = {
        @FaultAction(className = UsuarioNoEncontrado_Exception.class, value = "http://webservices/publicadorUsuario/infoUsuario/Fault/UsuarioNoEncontrado")
    })
    public DataUsuario infoUsuario(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0)
        throws UsuarioNoEncontrado_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns webservices.DtOrganizador
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices/publicadorUsuario/infoOrganizadorRequest", output = "http://webservices/publicadorUsuario/infoOrganizadorResponse")
    public DtOrganizador infoOrganizador(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg2
     * @param arg3
     * @param arg4
     * @param arg5
     * @throws EmailRepetido_Exception
     * @throws Exception_Exception
     * @throws NombreUsuarioExistente_Exception
     */
    @WebMethod
    @Action(input = "http://webservices/publicadorUsuario/ingresarAsistenteRequest", output = "http://webservices/publicadorUsuario/ingresarAsistenteResponse", fault = {
        @FaultAction(className = NombreUsuarioExistente_Exception.class, value = "http://webservices/publicadorUsuario/ingresarAsistente/Fault/NombreUsuarioExistente"),
        @FaultAction(className = EmailRepetido_Exception.class, value = "http://webservices/publicadorUsuario/ingresarAsistente/Fault/EmailRepetido"),
        @FaultAction(className = Exception_Exception.class, value = "http://webservices/publicadorUsuario/ingresarAsistente/Fault/Exception")
    })
    public void ingresarAsistente(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2,
        @WebParam(name = "arg3", partName = "arg3")
        String arg3,
        @WebParam(name = "arg4", partName = "arg4")
        String arg4,
        @WebParam(name = "arg5", partName = "arg5")
        String arg5)
        throws EmailRepetido_Exception, Exception_Exception, NombreUsuarioExistente_Exception
    ;

    /**
     * 
     * @param arg0
     * @param arg1
     */
    @WebMethod
    @Action(input = "http://webservices/publicadorUsuario/agregarAsistenteRequest", output = "http://webservices/publicadorUsuario/agregarAsistenteResponse")
    public void agregarAsistente(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1);

    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg2
     * @param arg3
     */
    @WebMethod
    @Action(input = "http://webservices/publicadorUsuario/editarOrganizadorRequest", output = "http://webservices/publicadorUsuario/editarOrganizadorResponse")
    public void editarOrganizador(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2,
        @WebParam(name = "arg3", partName = "arg3")
        String arg3);

    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg2
     * @param arg3
     */
    @WebMethod
    @Action(input = "http://webservices/publicadorUsuario/editarAsistenteRequest", output = "http://webservices/publicadorUsuario/editarAsistenteResponse")
    public void editarAsistente(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2,
        @WebParam(name = "arg3", partName = "arg3")
        String arg3);

    /**
     * 
     * @return
     *     returns webservices.WrapperHashSet
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices/publicadorUsuario/listarAsistentesRequest", output = "http://webservices/publicadorUsuario/listarAsistentesResponse")
    public WrapperHashSet listarAsistentes();

    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg2
     * @param arg3
     * @param arg4
     * @param arg5
     * @throws EmailRepetido_Exception
     * @throws Exception_Exception
     * @throws NombreUsuarioExistente_Exception
     */
    @WebMethod
    @Action(input = "http://webservices/publicadorUsuario/ingresarOrganizadorRequest", output = "http://webservices/publicadorUsuario/ingresarOrganizadorResponse", fault = {
        @FaultAction(className = NombreUsuarioExistente_Exception.class, value = "http://webservices/publicadorUsuario/ingresarOrganizador/Fault/NombreUsuarioExistente"),
        @FaultAction(className = EmailRepetido_Exception.class, value = "http://webservices/publicadorUsuario/ingresarOrganizador/Fault/EmailRepetido"),
        @FaultAction(className = Exception_Exception.class, value = "http://webservices/publicadorUsuario/ingresarOrganizador/Fault/Exception")
    })
    public void ingresarOrganizador(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2,
        @WebParam(name = "arg3", partName = "arg3")
        String arg3,
        @WebParam(name = "arg4", partName = "arg4")
        String arg4,
        @WebParam(name = "arg5", partName = "arg5")
        String arg5)
        throws EmailRepetido_Exception, Exception_Exception, NombreUsuarioExistente_Exception
    ;

    /**
     * 
     * @return
     *     returns webservices.WrapperHashSet
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices/publicadorUsuario/listarOrganizadoresRequest", output = "http://webservices/publicadorUsuario/listarOrganizadoresResponse")
    public WrapperHashSet listarOrganizadores();

    /**
     * 
     * @param arg0
     * @return
     *     returns webservices.WrapperHashSet
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices/publicadorUsuario/listarEdicionesOrganizadasRequest", output = "http://webservices/publicadorUsuario/listarEdicionesOrganizadasResponse")
    public WrapperHashSet listarEdicionesOrganizadas(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns webservices.WrapperHashSet
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices/publicadorUsuario/listarRegistrosAEventosRequest", output = "http://webservices/publicadorUsuario/listarRegistrosAEventosResponse")
    public WrapperHashSet listarRegistrosAEventos(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @param arg1
     * @return
     *     returns webservices.DataUsuario
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices/publicadorUsuario/iniciarSesionEmailRequest", output = "http://webservices/publicadorUsuario/iniciarSesionEmailResponse")
    public DataUsuario iniciarSesionEmail(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices/publicadorUsuario/existeNicknameRequest", output = "http://webservices/publicadorUsuario/existeNicknameResponse")
    public boolean existeNickname(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices/publicadorUsuario/existeEmailRequest", output = "http://webservices/publicadorUsuario/existeEmailResponse")
    public boolean existeEmail(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @param arg1
     * @throws UsuarioNoEncontrado_Exception
     */
    @WebMethod
    @Action(input = "http://webservices/publicadorUsuario/seguirUsuarioRequest", output = "http://webservices/publicadorUsuario/seguirUsuarioResponse", fault = {
        @FaultAction(className = UsuarioNoEncontrado_Exception.class, value = "http://webservices/publicadorUsuario/seguirUsuario/Fault/UsuarioNoEncontrado")
    })
    public void seguirUsuario(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1)
        throws UsuarioNoEncontrado_Exception
    ;

    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg2
     * @throws Exception_Exception
     * @throws NombreInstiExistente_Exception
     */
    @WebMethod
    @Action(input = "http://webservices/publicadorUsuario/altaInstitucionRequest", output = "http://webservices/publicadorUsuario/altaInstitucionResponse", fault = {
        @FaultAction(className = NombreInstiExistente_Exception.class, value = "http://webservices/publicadorUsuario/altaInstitucion/Fault/NombreInstiExistente"),
        @FaultAction(className = Exception_Exception.class, value = "http://webservices/publicadorUsuario/altaInstitucion/Fault/Exception")
    })
    public void altaInstitucion(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2)
        throws Exception_Exception, NombreInstiExistente_Exception
    ;

    /**
     * 
     * @return
     *     returns webservices.WrapperHashSet
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices/publicadorUsuario/listarInstitucionesRequest", output = "http://webservices/publicadorUsuario/listarInstitucionesResponse")
    public WrapperHashSet listarInstituciones();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices/publicadorUsuario/obtenerInstitucionAsistenteRequest", output = "http://webservices/publicadorUsuario/obtenerInstitucionAsistenteResponse")
    public String obtenerInstitucionAsistente(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @param arg1
     * @return
     *     returns webservices.DataUsuario
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices/publicadorUsuario/iniciarSesionNicknameRequest", output = "http://webservices/publicadorUsuario/iniciarSesionNicknameResponse")
    public DataUsuario iniciarSesionNickname(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1);

    /**
     * 
     * @param arg0
     * @param arg1
     * @throws UsuarioNoEncontrado_Exception
     */
    @WebMethod
    @Action(input = "http://webservices/publicadorUsuario/dejarDeSeguirUsuarioRequest", output = "http://webservices/publicadorUsuario/dejarDeSeguirUsuarioResponse", fault = {
        @FaultAction(className = UsuarioNoEncontrado_Exception.class, value = "http://webservices/publicadorUsuario/dejarDeSeguirUsuario/Fault/UsuarioNoEncontrado")
    })
    public void dejarDeSeguirUsuario(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1)
        throws UsuarioNoEncontrado_Exception
    ;

    /**
     * 
     * @param arg0
     * @param arg1
     * @return
     *     returns boolean
     * @throws UsuarioNoEncontrado_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices/publicadorUsuario/esSeguidorRequest", output = "http://webservices/publicadorUsuario/esSeguidorResponse", fault = {
        @FaultAction(className = UsuarioNoEncontrado_Exception.class, value = "http://webservices/publicadorUsuario/esSeguidor/Fault/UsuarioNoEncontrado")
    })
    public boolean esSeguidor(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1)
        throws UsuarioNoEncontrado_Exception
    ;

}
