
package webservices;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.FaultAction;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "publicadorEvento", targetNamespace = "http://webservices/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PublicadorEvento {


    /**
     * 
     * @param fileName
     * @return
     *     returns byte[]
     * @throws IOException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices/publicadorEvento/getFileRequest", output = "http://webservices/publicadorEvento/getFileResponse", fault = {
        @FaultAction(className = IOException_Exception.class, value = "http://webservices/publicadorEvento/getFile/Fault/IOException")
    })
    public byte[] getFile(
        @WebParam(name = "fileName", partName = "fileName")
        String fileName)
        throws IOException_Exception
    ;

    /**
     * 
     * @return
     *     returns webservices.WrapperHashSet
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices/publicadorEvento/listarEventosRequest", output = "http://webservices/publicadorEvento/listarEventosResponse")
    public WrapperHashSet listarEventos();

    /**
     * 
     * @return
     *     returns webservices.WrapperHashSet
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices/publicadorEvento/listarEdicionesTodasRequest", output = "http://webservices/publicadorEvento/listarEdicionesTodasResponse")
    public WrapperHashSet listarEdicionesTodas();

    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg2
     * @param arg3
     * @param arg4
     * @param arg5
     * @throws Exception_Exception
     * @throws NombreEventoExcepcion_Exception
     */
    @WebMethod
    @Action(input = "http://webservices/publicadorEvento/altaEventoRequest", output = "http://webservices/publicadorEvento/altaEventoResponse", fault = {
        @FaultAction(className = NombreEventoExcepcion_Exception.class, value = "http://webservices/publicadorEvento/altaEvento/Fault/NombreEventoExcepcion"),
        @FaultAction(className = Exception_Exception.class, value = "http://webservices/publicadorEvento/altaEvento/Fault/Exception")
    })
    public void altaEvento(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2,
        @WebParam(name = "arg3", partName = "arg3")
        String arg3,
        @WebParam(name = "arg4", partName = "arg4")
        WrapperHashSet arg4,
        @WebParam(name = "arg5", partName = "arg5")
        String arg5)
        throws Exception_Exception, NombreEventoExcepcion_Exception
    ;

    /**
     * 
     * @return
     *     returns webservices.WrapperHashSet
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices/publicadorEvento/listarCategoriasRequest", output = "http://webservices/publicadorEvento/listarCategoriasResponse")
    public WrapperHashSet listarCategorias();

    /**
     * 
     * @param arg0
     * @return
     *     returns webservices.WrapperHashSet
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices/publicadorEvento/listarEdicionesRequest", output = "http://webservices/publicadorEvento/listarEdicionesResponse")
    public WrapperHashSet listarEdiciones(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns webservices.WrapperHashSet
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices/publicadorEvento/listarPatrociniosRequest", output = "http://webservices/publicadorEvento/listarPatrociniosResponse")
    public WrapperHashSet listarPatrocinios(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @param arg1
     * @return
     *     returns webservices.DtPatrocinio
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices/publicadorEvento/obtenerPatrocinioRequest", output = "http://webservices/publicadorEvento/obtenerPatrocinioResponse")
    public DtPatrocinio obtenerPatrocinio(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns webservices.DtDetalleEdicion
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices/publicadorEvento/mostrarDetallesEdicionRequest", output = "http://webservices/publicadorEvento/mostrarDetallesEdicionResponse")
    public DtDetalleEdicion mostrarDetallesEdicion(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @param arg1
     * @return
     *     returns webservices.DtTipoRegistro
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices/publicadorEvento/verDetalleTRegistroRequest", output = "http://webservices/publicadorEvento/verDetalleTRegistroResponse")
    public DtTipoRegistro verDetalleTRegistro(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1);

    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg2
     * @param arg3
     * @param arg4
     * @throws Exception_Exception
     * @throws TipoRegistroExistenteExcepcion_Exception
     */
    @WebMethod
    @Action(input = "http://webservices/publicadorEvento/altaTipoDeRegistroRequest", output = "http://webservices/publicadorEvento/altaTipoDeRegistroResponse", fault = {
        @FaultAction(className = TipoRegistroExistenteExcepcion_Exception.class, value = "http://webservices/publicadorEvento/altaTipoDeRegistro/Fault/TipoRegistroExistenteExcepcion"),
        @FaultAction(className = Exception_Exception.class, value = "http://webservices/publicadorEvento/altaTipoDeRegistro/Fault/Exception")
    })
    public void altaTipoDeRegistro(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2,
        @WebParam(name = "arg3", partName = "arg3")
        float arg3,
        @WebParam(name = "arg4", partName = "arg4")
        int arg4)
        throws Exception_Exception, TipoRegistroExistenteExcepcion_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns webservices.DtDetalleEvento
     * @throws EventoFinalizadoExcepcion_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices/publicadorEvento/verDetalleEventoRequest", output = "http://webservices/publicadorEvento/verDetalleEventoResponse", fault = {
        @FaultAction(className = EventoFinalizadoExcepcion_Exception.class, value = "http://webservices/publicadorEvento/verDetalleEvento/Fault/EventoFinalizadoExcepcion")
    })
    public DtDetalleEvento verDetalleEvento(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0)
        throws EventoFinalizadoExcepcion_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns webservices.WrapperHashSet
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices/publicadorEvento/listarTiposDeRegistroRequest", output = "http://webservices/publicadorEvento/listarTiposDeRegistroResponse")
    public WrapperHashSet listarTiposDeRegistro(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @param arg1
     * @return
     *     returns webservices.DtRegistro
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices/publicadorEvento/infoRegistroRequest", output = "http://webservices/publicadorEvento/infoRegistroResponse")
    public DtRegistro infoRegistro(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1);

    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg2
     * @param arg3
     * @param arg4
     * @param arg5
     * @param arg6
     * @param arg7
     * @param arg8
     * @param arg9
     * @throws Exception_Exception
     * @throws FechaInicioPOSTFINAL_Exception
     * @throws FechaInicioPREALTA_Exception
     * @throws NombreEdicionExistenteExcepcion_Exception
     */
    @WebMethod
    @Action(input = "http://webservices/publicadorEvento/altaEdicionDeEventoRequest", output = "http://webservices/publicadorEvento/altaEdicionDeEventoResponse", fault = {
        @FaultAction(className = NombreEdicionExistenteExcepcion_Exception.class, value = "http://webservices/publicadorEvento/altaEdicionDeEvento/Fault/NombreEdicionExistenteExcepcion"),
        @FaultAction(className = FechaInicioPOSTFINAL_Exception.class, value = "http://webservices/publicadorEvento/altaEdicionDeEvento/Fault/FechaInicioPOSTFINAL"),
        @FaultAction(className = FechaInicioPREALTA_Exception.class, value = "http://webservices/publicadorEvento/altaEdicionDeEvento/Fault/FechaInicioPREALTA"),
        @FaultAction(className = Exception_Exception.class, value = "http://webservices/publicadorEvento/altaEdicionDeEvento/Fault/Exception")
    })
    public void altaEdicionDeEvento(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2,
        @WebParam(name = "arg3", partName = "arg3")
        String arg3,
        @WebParam(name = "arg4", partName = "arg4")
        String arg4,
        @WebParam(name = "arg5", partName = "arg5")
        String arg5,
        @WebParam(name = "arg6", partName = "arg6")
        String arg6,
        @WebParam(name = "arg7", partName = "arg7")
        String arg7,
        @WebParam(name = "arg8", partName = "arg8")
        String arg8,
        @WebParam(name = "arg9", partName = "arg9")
        String arg9)
        throws Exception_Exception, FechaInicioPOSTFINAL_Exception, FechaInicioPREALTA_Exception, NombreEdicionExistenteExcepcion_Exception
    ;

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @Action(input = "http://webservices/publicadorEvento/ingresarCategoriaRequest", output = "http://webservices/publicadorEvento/ingresarCategoriaResponse")
    public void ingresarCategoria(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns webservices.WrapperHashSet
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices/publicadorEvento/listarAsistentesAEdicionDeEventoRequest", output = "http://webservices/publicadorEvento/listarAsistentesAEdicionDeEventoResponse")
    public WrapperHashSet listarAsistentesAEdicionDeEvento(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg2
     * @param arg3
     * @throws AsistenteYaRegistrado_Exception
     * @throws CupoLLeno_Exception
     * @throws Exception_Exception
     * @throws FechaInicioPREALTA_Exception
     */
    @WebMethod
    @Action(input = "http://webservices/publicadorEvento/elegirAsistenteYTipoRegistroRequest", output = "http://webservices/publicadorEvento/elegirAsistenteYTipoRegistroResponse", fault = {
        @FaultAction(className = FechaInicioPREALTA_Exception.class, value = "http://webservices/publicadorEvento/elegirAsistenteYTipoRegistro/Fault/FechaInicioPREALTA"),
        @FaultAction(className = CupoLLeno_Exception.class, value = "http://webservices/publicadorEvento/elegirAsistenteYTipoRegistro/Fault/CupoLLeno"),
        @FaultAction(className = AsistenteYaRegistrado_Exception.class, value = "http://webservices/publicadorEvento/elegirAsistenteYTipoRegistro/Fault/AsistenteYaRegistrado"),
        @FaultAction(className = Exception_Exception.class, value = "http://webservices/publicadorEvento/elegirAsistenteYTipoRegistro/Fault/Exception")
    })
    public void elegirAsistenteYTipoRegistro(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2,
        @WebParam(name = "arg3", partName = "arg3")
        boolean arg3)
        throws AsistenteYaRegistrado_Exception, CupoLLeno_Exception, Exception_Exception, FechaInicioPREALTA_Exception
    ;

    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg2
     * @param arg3
     * @throws Exception_Exception
     */
    @WebMethod
    @Action(input = "http://webservices/publicadorEvento/altaRegistroRequest", output = "http://webservices/publicadorEvento/altaRegistroResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://webservices/publicadorEvento/altaRegistro/Fault/Exception")
    })
    public void altaRegistro(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2,
        @WebParam(name = "arg3", partName = "arg3")
        boolean arg3)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg2
     * @param arg3
     * @param arg4
     * @param arg5
     * @param arg6
     */
    @WebMethod
    @Action(input = "http://webservices/publicadorEvento/altaPatrocinioRequest", output = "http://webservices/publicadorEvento/altaPatrocinioResponse")
    public void altaPatrocinio(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        NivelPatrocinio arg2,
        @WebParam(name = "arg3", partName = "arg3")
        double arg3,
        @WebParam(name = "arg4", partName = "arg4")
        String arg4,
        @WebParam(name = "arg5", partName = "arg5")
        int arg5,
        @WebParam(name = "arg6", partName = "arg6")
        String arg6);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices/publicadorEvento/getFechaSistemaRequest", output = "http://webservices/publicadorEvento/getFechaSistemaResponse")
    public String getFechaSistema();

    /**
     * 
     * @param arg0
     * @return
     *     returns webservices.LocalDate
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices/publicadorEvento/setFechaSistemaRequest", output = "http://webservices/publicadorEvento/setFechaSistemaResponse")
    public LocalDate setFechaSistema(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices/publicadorEvento/nomEvPorEdRequest", output = "http://webservices/publicadorEvento/nomEvPorEdResponse")
    public String nomEvPorEd(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @param arg1
     */
    @WebMethod
    @Action(input = "http://webservices/publicadorEvento/aceptarEdicionRequest", output = "http://webservices/publicadorEvento/aceptarEdicionResponse")
    public void aceptarEdicion(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1);

    /**
     * 
     * @param arg0
     * @param arg1
     */
    @WebMethod
    @Action(input = "http://webservices/publicadorEvento/rechazarEdicionRequest", output = "http://webservices/publicadorEvento/rechazarEdicionResponse")
    public void rechazarEdicion(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns webservices.WrapperHashSet
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices/publicadorEvento/listarEdicionesConfirmadasRequest", output = "http://webservices/publicadorEvento/listarEdicionesConfirmadasResponse")
    public WrapperHashSet listarEdicionesConfirmadas(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns webservices.WrapperHashSet
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices/publicadorEvento/listarEdicionesPendientesRequest", output = "http://webservices/publicadorEvento/listarEdicionesPendientesResponse")
    public WrapperHashSet listarEdicionesPendientes(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @return
     *     returns webservices.WrapperHashSet
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices/publicadorEvento/obtenerEventosRecientesRequest", output = "http://webservices/publicadorEvento/obtenerEventosRecientesResponse")
    public WrapperHashSet obtenerEventosRecientes();

    /**
     * 
     * @param arg0
     * @param arg1
     */
    @WebMethod(operationName = "ConfirmarAsistencia")
    @Action(input = "http://webservices/publicadorEvento/ConfirmarAsistenciaRequest", output = "http://webservices/publicadorEvento/ConfirmarAsistenciaResponse")
    public void confirmarAsistencia(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @Action(input = "http://webservices/publicadorEvento/finalizarEventoRequest", output = "http://webservices/publicadorEvento/finalizarEventoResponse")
    public void finalizarEvento(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param nombreEvento
     */
    @WebMethod
    @Action(input = "http://webservices/publicadorEvento/registrarVisitaEventoRequest", output = "http://webservices/publicadorEvento/registrarVisitaEventoResponse")
    public void registrarVisitaEvento(
        @WebParam(name = "nombreEvento", partName = "nombreEvento")
        String nombreEvento);

}
