package webservices;

import java.io.FileInputStream;
import java.net.MalformedURLException;
import java.net.URL;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Properties;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "publicadorImagenesService", targetNamespace = "http://webservices/")
public class PublicadorImagenesService
    extends Service
{

    private final static URL PUBLICADORIMAGENESSERVICE_WSDL_LOCATION;
    private final static WebServiceException PUBLICADORIMAGENESSERVICE_EXCEPTION;
    private final static QName PUBLICADORIMAGENESSERVICE_QNAME = new QName("http://webservices/", "publicadorImagenesService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            Properties props = new Properties();
            
            // Buscar application.properties en el home del usuario (según Sección 7.9)
            String userHome = System.getProperty("user.home");
            String configPath = userHome + "/application.properties";
            
            FileInputStream fis = new FileInputStream(configPath);
            props.load(fis);
            fis.close();
            
            String serverUrl = props.getProperty("server.url", "http://localhost");
            String serverPort = props.getProperty("server.port", "8080");
            String wsdlUrl = serverUrl + ":" + serverPort + "/publicadorImagenes?WSDL";
            url = new URL(wsdlUrl);
        } catch (java.lang.Exception ex) {
            e = new WebServiceException(ex);
        }
        PUBLICADORIMAGENESSERVICE_WSDL_LOCATION = url;
        PUBLICADORIMAGENESSERVICE_EXCEPTION = e;
    }

    public PublicadorImagenesService() {
        super(__getWsdlLocation(), PUBLICADORIMAGENESSERVICE_QNAME);
    }

    public PublicadorImagenesService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PUBLICADORIMAGENESSERVICE_QNAME, features);
    }

    public PublicadorImagenesService(URL wsdlLocation) {
        super(wsdlLocation, PUBLICADORIMAGENESSERVICE_QNAME);
    }

    public PublicadorImagenesService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PUBLICADORIMAGENESSERVICE_QNAME, features);
    }

    public PublicadorImagenesService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PublicadorImagenesService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PublicadorImagenes
     */
    @WebEndpoint(name = "publicadorImagenesPort")
    public PublicadorImagenes getPublicadorImagenesPort() {
        return super.getPort(new QName("http://webservices/", "publicadorImagenesPort"), PublicadorImagenes.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PublicadorImagenes
     */
    @WebEndpoint(name = "publicadorImagenesPort")
    public PublicadorImagenes getPublicadorImagenesPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservices/", "publicadorImagenesPort"), PublicadorImagenes.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PUBLICADORIMAGENESSERVICE_EXCEPTION!= null) {
            throw PUBLICADORIMAGENESSERVICE_EXCEPTION;
        }
        return PUBLICADORIMAGENESSERVICE_WSDL_LOCATION;
    }

}