
package webservices;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebFault(name = "TipoRegistroExistenteExcepcion", targetNamespace = "http://webservices/")
public class TipoRegistroExistenteExcepcion_Exception
    extends java.lang.Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private TipoRegistroExistenteExcepcion faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public TipoRegistroExistenteExcepcion_Exception(String message, TipoRegistroExistenteExcepcion faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param cause
     * @param faultInfo
     * @param message
     */
    public TipoRegistroExistenteExcepcion_Exception(String message, TipoRegistroExistenteExcepcion faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: webservices.TipoRegistroExistenteExcepcion
     */
    public TipoRegistroExistenteExcepcion getFaultInfo() {
        return faultInfo;
    }

}
