/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.13
 * Generated at: 2025-12-05 18:35:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.pages;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.HashSet;
import java.util.Set;
import webservices.*;
import java.util.GregorianCalendar;
import javax.xml.datatype.XMLGregorianCalendar;
import java.time.LocalDate;

public final class detalleEdicion_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {


	// Función Java para convertir URL de YouTube a formato embed
	private String convertToEmbedUrl(String youtubeUrl) {
		if (youtubeUrl == null || youtubeUrl.trim().isEmpty()) {
			return null;
		}
		
		try {
			// Patrones comunes de URL de YouTube
			String videoId = null;
			
			// Para URLs como: https://www.youtube.com/watch?v=VIDEO_ID
			if (youtubeUrl.contains("youtube.com/watch?v=")) {
				int startIndex = youtubeUrl.indexOf("v=") + 2;
				int endIndex = youtubeUrl.indexOf("&", startIndex);
				if (endIndex == -1) {
					endIndex = youtubeUrl.length();
				}
				videoId = youtubeUrl.substring(startIndex, endIndex);
			}
			// Para URLs como: https://youtu.be/VIDEO_ID
			else if (youtubeUrl.contains("youtu.be/")) {
				int startIndex = youtubeUrl.lastIndexOf("/") + 1;
				int endIndex = youtubeUrl.indexOf("?", startIndex);
				if (endIndex == -1) {
					endIndex = youtubeUrl.length();
				}
				videoId = youtubeUrl.substring(startIndex, endIndex);
			}
			// Para URLs que ya están en formato embed
			else if (youtubeUrl.contains("youtube.com/embed/")) {
				return youtubeUrl;
			}
			
			// Si encontramos el video ID, construir URL embed
			if (videoId != null && !videoId.isEmpty()) {
				return "https://www.youtube.com/embed/" + videoId;
			}
		} catch (java.lang.Exception e) {
			// En caso de error, no mostrar video
			return null;
		}
		
		return null;
	}

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("webservices");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(7);
    _jspx_imports_classes.add("java.util.HashSet");
    _jspx_imports_classes.add("java.util.GregorianCalendar");
    _jspx_imports_classes.add("java.time.LocalDate");
    _jspx_imports_classes.add("java.util.Set");
    _jspx_imports_classes.add("javax.xml.datatype.XMLGregorianCalendar");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"es\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<title>Consulta Edición</title>\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/ConsultaEvento.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/styles.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://fonts.googleapis.com/css2?family=Inter&display=swap\" />\r\n");
      out.write("<link rel=\"icon\" type=\"image/x-icon\" href=\"assets/icons/Logo.png\">\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/boxicons@latest/css/boxicons.min.css\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("	");
 DataUsuario user = (DataUsuario) session.getAttribute("usuario");  
      out.write('\r');
      out.write('\n');
      out.write('	');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../templates/header.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<div class=\"container px-4 \">\r\n");
      out.write("	\r\n");
      out.write("	</div>\r\n");
      out.write("	<div class=\"container px-4 mt-3\">\r\n");
      out.write("		<div class=\"row pb-4\">\r\n");
      out.write("			<!-- Imagen de la edición y categorias-->\r\n");
      out.write("			");
 DtDetalleEdicion edi = (DtDetalleEdicion) request.getAttribute("edicion");
      out.write("\r\n");
      out.write("			<div class=\"col-md-3 col-lg-3 col-xl-3 \">\r\n");
      out.write("				<img src=\"");
      out.print( request.getAttribute("imagenEdicion") );
      out.write("\"\r\n");
      out.write("					alt=\"");
      out.print( request.getAttribute("nombre") );
      out.write("\" class=\"img-fluid rounded\"\r\n");
      out.write("					style=\"width: 100%; height: 180px; object-fit: cover; aspect-ratio: 1/1;\">\r\n");
      out.write("					");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../templates/categorias-sidebar.jsp", out, false);
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("			<!-- Información principal de la edición -->\r\n");
      out.write("			<div class=\"col-md-9 col-lg-9 col-xl-9 mt-3 mt-md-0 info-evento px-5\">\r\n");
      out.write("				<div class=\"d-flex align-items-center gap-3 mb-2\">\r\n");
      out.write("					<h2 class=\"fw-bold mb-0\"> ");
      out.print( edi.getNombre() );
      out.write("</h2>\r\n");
      out.write("					");

					// Mostrar tag de estado solo si es organizador de la edición
					if (user != null && user.getTipo() == TipoUsuario.ORGANIZADOR) { 
						boolean esOrg = (boolean) request.getAttribute("esOrganizador");
						if (esOrg) {
							String estadoClass = "";
							String estadoTexto = "";
							EstadoEdicion estado = edi.getEstado();
							
							switch(estado) {
								case CONFIRMADA:
									estadoClass = "badge bg-success";
									estadoTexto = "Confirmada";
									break;
								case INGRESADA:
									estadoClass = "badge bg-warning text-dark";
									estadoTexto = "Pendiente";
									break;
								case RECHAZADA:
									estadoClass = "badge bg-danger";
									estadoTexto = "Rechazada";
									break;
							}
					
      out.write("\r\n");
      out.write("					<span class=\"");
      out.print( estadoClass );
      out.write('"');
      out.write('>');
      out.print( estadoTexto );
      out.write("</span>\r\n");
      out.write("					");
 }} 
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"mb-2 d-flex align-items-center\">\r\n");
      out.write("					<strong class=\"me-2\">Organizador:</strong> <a\r\n");
      out.write("						href=\"detalleUsuario?usuarios=");
      out.print( edi.getOrganizador() );
      out.write("\"\r\n");
      out.write("						class=\"d-flex align-items-center text-decoration-none\"> <img\r\n");
      out.write("					");
 
					String imagenOrganizador = (String) request.getAttribute("imagenOrganizador");
					String nombre = (String) request.getAttribute("nombre");
					
      out.write("\r\n");
      out.write("					src=\"");
      out.print( imagenOrganizador );
      out.write("\" alt=\"");
      out.print( edi.getOrganizador() );
      out.write("\"\r\n");
      out.write("					class=\"rounded-circle me-2\"\r\n");
      out.write("					style=\"width: 32px; height: 32px; object-fit: cover; border: 1px solid rgba(0, 0, 0, .06);\">\r\n");
      out.write("					<span class=\"fw-bold text-dark\">");
      out.print( edi.getOrganizador() );
      out.write("</span>\r\n");
      out.write("				</a>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"mb-2 d-flex align-items-center\">\r\n");
      out.write("					");
 
					String imagenEvento = (String) request.getAttribute("imagenEvento");
					String nombreEvento = (String) request.getAttribute("nombreEvento");
					
      out.write("\r\n");
      out.write("					<strong class=\"me-2\">Evento:</strong> <a\r\n");
      out.write("						href=\"detalleEvento?nombre=");
      out.print( nombreEvento );
      out.write("\"\r\n");
      out.write("						class=\"d-flex align-items-center text-decoration-none\"> <img\r\n");
      out.write("					src=\"");
      out.print( imagenEvento );
      out.write("\" alt=\"");
      out.print( nombreEvento );
      out.write("\"\r\n");
      out.write("					class=\"rounded-circle me-2\"\r\n");
      out.write("					style=\"width: 32px; height: 32px; object-fit: cover; border: 1px solid rgba(0, 0, 0, .06);\">\r\n");
      out.write("					<span class=\"fw-bold text-dark\">");
      out.print( nombreEvento );
      out.write("</span>\r\n");
      out.write("				</a>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"mb-2 d-flex align-items-center\">\r\n");
      out.write("					<strong class=\"me-2\">Sigla:</strong> <span\r\n");
      out.write("						class=\"fw-bold text-dark\">");
      out.print( edi.getSigla() );
      out.write("</span>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"mb-2\">\r\n");
      out.write("					<strong>Fecha inicio:</strong> ");
      out.print( edi.getFechaInicio() );
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"mb-2\">\r\n");
      out.write("					<strong>Fecha fin:</strong> ");
      out.print( edi.getFechaFin() );
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"mb-2\">\r\n");
      out.write("					<strong>Fecha alta:</strong> ");
      out.print( edi.getFechaAlta() );
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"mb-2\">\r\n");
      out.write("					<strong>País:</strong> ");
      out.print( edi.getPais() );
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"mb-2\">\r\n");
      out.write("					<strong>Ciudad:</strong> ");
      out.print( edi.getCiudad() );
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("				");

				boolean esOrganizador = false;
				if (user != null && user.getTipo() == TipoUsuario.ORGANIZADOR) { 
					esOrganizador = (boolean) request.getAttribute("esOrganizador");
					if ((boolean) request.getAttribute("esOrganizador") == true 
						&& edi.getEstado() != EstadoEdicion.INGRESADA 
						&& edi.getEstado() != EstadoEdicion.RECHAZADA) {
				
      out.write("\r\n");
      out.write("				<div class=\"mt-4\">\r\n");
      out.write("					<a href=\"listar-registros?edicion=");
      out.print( edi.getNombre() );
      out.write("\" style=\"text-decoration: none;\">\r\n");
      out.write("						<button class=\"button2 rounded-3 p-3\">\r\n");
      out.write("							<div class=\"header-button\">Ver Registros</div>\r\n");
      out.write("						</button>\r\n");
      out.write("					</a>\r\n");
      out.write("				</div> ");
 }} else if (user != null) {
					boolean usuarioRegistrado = (boolean) request.getAttribute("usuarioRegistrado");
					if (!usuarioRegistrado) {
						LocalDate fechaActual = (LocalDate) session.getAttribute("fecha");
						XMLGregorianCalendar fechaFin = edi.getFechaFin();
						if (fechaActual.isAfter(fechaFin.toGregorianCalendar().toZonedDateTime().toLocalDate()) ) {
					
      out.write(" \r\n");
      out.write("					<div class=\"alert alert-secondary text-center mb-0\" role=\"alert\">\r\n");
      out.write("						Esta edición ya finalizó.</div>\r\n");
      out.write("					");
 } else { 
      out.write("\r\n");
      out.write("				<div class=\"mt-4\">\r\n");
      out.write("					<a href=\"altaRegistro?edicion=");
      out.print( edi.getNombre() );
      out.write("\" style=\"text-decoration: none;\">\r\n");
      out.write("						<button class=\"btn btn-success rounded-3 p-3\">\r\n");
      out.write("							<div class=\"header-button\">Registrarse a la Edicion</div>\r\n");
      out.write("						</button>\r\n");
      out.write("					</a>\r\n");
      out.write("				</div> ");
 }} else { 
      out.write("\r\n");
      out.write("				<div class=\"mt-4\">\r\n");
      out.write("					<a href=\"ver-registro?edicion=");
      out.print( edi.getNombre()  );
      out.write("&usuario=");
      out.print( user.getNickname() );
      out.write("\" style=\"text-decoration: none;\">\r\n");
      out.write("						<button class=\"button2 rounded-3 p-3\">\r\n");
      out.write("							<div class=\"header-button\">Ver detalle del Registro</div>\r\n");
      out.write("						</button>\r\n");
      out.write("					</a>\r\n");
      out.write("				</div> ");
 }} 
      out.write("\r\n");
      out.write("\r\n");
      out.write("				<!-- Tipos de registros -->\r\n");
      out.write("				<div class=\"mt-4\">\r\n");
      out.write("				\r\n");
      out.write("					<div class=\"d-flex align-items-baseline gap-2\">\r\n");
      out.write("						<h5 class=\"py-2\">Tipos de Registro</h5>\r\n");
      out.write("						");
 
						if (user != null && user.getTipo() == TipoUsuario.ORGANIZADOR && esOrganizador) {
							LocalDate fechaActual2 = (LocalDate) session.getAttribute("fecha");
							XMLGregorianCalendar fechaFin2 = edi.getFechaFin();
							if (fechaActual2.isBefore(fechaFin2.toGregorianCalendar().toZonedDateTime().toLocalDate()) 
								&& edi.getEstado() != EstadoEdicion.RECHAZADA) {
						
      out.write("\r\n");
      out.write("						<a href=\"/tarea2/alta-tipo-registro?edicion=");
      out.print( edi.getNombre() );
      out.write("\" class=\"btn btn-success btn-sm\"\r\n");
      out.write("							title=\"Agregar tipo de registro\"> <i class=\"bi bi-plus-lg\"></i>\r\n");
      out.write("						</a> ");
 }} 
      out.write("\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"accordion\" id=\"accordionTiposRegistro\">\r\n");
      out.write("					");
 
					@SuppressWarnings("unchecked")
					Set<DtTipoRegistro> trSet = (Set<DtTipoRegistro>) request.getAttribute("tiposRegistro");
					if (trSet.isEmpty()) {
						
      out.write(" 	<div class=\"alert alert-secondary text-center mb-0\" role=\"alert\">\r\n");
      out.write("						Aún no existen tipos de registro para esta edición.</div>\r\n");
      out.write("					");
} else { 
						int i = 0;
						for (DtTipoRegistro tipoReg : trSet) {
					
      out.write("\r\n");
      out.write("						<div class=\"accordion-item\">\r\n");
      out.write("							<h2 class=\"accordion-header\" id=\"heading");
      out.print( i );
      out.write("\">\r\n");
      out.write("								<button class=\"accordion-button collapsed\" type=\"button\"\r\n");
      out.write("									data-bs-toggle=\"collapse\" data-bs-target=\"#collapse");
      out.print( i );
      out.write("\"\r\n");
      out.write("									aria-expanded=\"false\" aria-controls=\"collapse");
      out.print( i );
      out.write("\">\r\n");
      out.write("									");
      out.print( tipoReg.getNombre() );
      out.write("</button>\r\n");
      out.write("							</h2>\r\n");
      out.write("							<div id=\"collapse");
      out.print( i );
      out.write("\" class=\"accordion-collapse collapse\"\r\n");
      out.write("								aria-labelledby=\"heading");
      out.print( i );
      out.write("\"\r\n");
      out.write("								data-bs-parent=\"#accordionTiposRegistro\">\r\n");
      out.write("								<div class=\"accordion-body registro-info \">\r\n");
      out.write("									<p>\r\n");
      out.write("										<strong>Costo:</strong> $");
      out.print( tipoReg.getCosto());
      out.write("\r\n");
      out.write("									</p>\r\n");
      out.write("									<p>\r\n");
      out.write("										<strong>Cupo:</strong> ");
      out.print( tipoReg.getCupo() );
      out.write("\r\n");
      out.write("									</p>\r\n");
      out.write("									<p>\r\n");
      out.write("										<strong>Descripción:</strong> ");
      out.print( tipoReg.getDescripcion() );
      out.write("\r\n");
      out.write("									</p>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div> ");
 i++;}} 
      out.write("\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<!-- Patrocinios -->\r\n");
      out.write("				<div class=\"mt-4\">\r\n");
      out.write("					<div class=\"d-flex align-items-baseline gap-2\">\r\n");
      out.write("						<h5 class=\"py-2\">Patrocinadores</h5>\r\n");
      out.write("						");
 
						if (user != null && user.getTipo() == TipoUsuario.ORGANIZADOR && esOrganizador) {
							LocalDate fechaActual3 = (LocalDate) session.getAttribute("fecha");
							XMLGregorianCalendar fechaFin3 = edi.getFechaFin();
							if (fechaActual3.isBefore(fechaFin3.toGregorianCalendar().toZonedDateTime().toLocalDate())
								&& edi.getEstado() != EstadoEdicion.RECHAZADA) {
						
      out.write("\r\n");
      out.write("						<a href=\"altaPatrocinio?nombreEdicion=");
      out.print( edi.getNombre() );
      out.write("\" class=\"btn btn-success btn-sm\"\r\n");
      out.write("							title=\"Agregar patrocinio\"> <i class=\"bi bi-plus-lg\"></i>\r\n");
      out.write("						</a> ");
 }} 
      out.write("\r\n");
      out.write("						\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"accordion\" id=\"accordionPatrocinadores\">\r\n");
      out.write("					");

					@SuppressWarnings("unchecked")
					Set<DtPatrocinio> patSet = (Set<DtPatrocinio>) request.getAttribute("patrocinios");
					if (patSet.isEmpty()) {
					
      out.write(" <div class=\"alert alert-secondary text-center mb-0\" role=\"alert\">\r\n");
      out.write("						Aún no existen patrocinios para esta edición.</div>\r\n");
      out.write("					");
} else { 
						for (DtPatrocinio patr : patSet) {
					
      out.write("\r\n");
      out.write("						<div class=\"accordion-item\">\r\n");
      out.write("							<h2 class=\"accordion-header\">\r\n");
      out.write("								<button class=\"accordion-button collapsed\" type=\"button\"\r\n");
      out.write("									data-bs-toggle=\"collapse\" data-bs-target=\"#collapse");
      out.print( patr.getCodigo() );
      out.write("\"\r\n");
      out.write("									aria-expanded=\"false\" aria-controls=\"collapse");
      out.print( patr.getCodigo() );
      out.write("\">\r\n");
      out.write("									");
      out.print( patr.getInstitucion() );
      out.write("</button>\r\n");
      out.write("							</h2>\r\n");
      out.write("							<div id=\"collapse");
      out.print( patr.getCodigo() );
      out.write("\" class=\"accordion-collapse collapse\"\r\n");
      out.write("								aria-labelledby=\"headingPatro\"\r\n");
      out.write("								data-bs-parent=\"#accordionPatrocinadores\">\r\n");
      out.write("								<div class=\"accordion-body registro-info\">\r\n");
      out.write("									<div class=\"d-flex align-items-center mb-2\">\r\n");
      out.write("										<span class=\"mb-0\"\r\n");
      out.write("											style=\"font-weight: 600; font-size: 1.2rem;\">");
      out.print( patr.getInstitucion() );
      out.write("</span>\r\n");
      out.write("									</div>\r\n");
      out.write("									<p>\r\n");
      out.write("										<strong>Nivel:</strong> ");
      out.print( patr.getNivelPatrocinio() );
      out.write("\r\n");
      out.write("									</p>\r\n");
      out.write("									<p>\r\n");
      out.write("										<strong>Tipo de Registro :</strong> ");
      out.print( patr.getTipoRegistroGratis() );
      out.write("\r\n");
      out.write("									</p>\r\n");
      out.write("									<p>\r\n");
      out.write("										<strong>Aporte:</strong> $");
      out.print( patr.getMonto() );
      out.write("\r\n");
      out.write("									</p>\r\n");
      out.write("									<p>\r\n");
      out.write("										<strong>Fecha:</strong> ");
      out.print( patr.getFecha() );
      out.write("\r\n");
      out.write("									</p>\r\n");
      out.write("									<p>\r\n");
      out.write("										<strong>Registros gratis:</strong> ");
      out.print( patr.getCantRegsGratis() );
      out.write("\r\n");
      out.write("									</p>\r\n");
      out.write("									<p>\r\n");
      out.write("										<strong>Código:</strong><span class=\"text-success\">\r\n");
      out.write("											");
      out.print( patr.getCodigo() );
      out.write("</span>\r\n");
      out.write("									</p>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div> ");
 }} 
      out.write("\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<!-- Sección de video de YouTube -->\r\n");
      out.write("				");

				String videoUrl = edi.getVideourl();
				if (videoUrl != null && !videoUrl.trim().isEmpty()) {
					// Convertir URL de YouTube a formato embed
					String embedUrl = convertToEmbedUrl(videoUrl.trim());
					if (embedUrl != null) {
				
      out.write("\r\n");
      out.write("					<div class=\"mt-4\">\r\n");
      out.write("						<h5 class=\"mb-3\"><i class=\"bi bi-play-circle\"></i> Video de la Edición</h5>\r\n");
      out.write("						<div class=\"ratio ratio-16x9\" style=\"max-width: 600px;\">\r\n");
      out.write("							<iframe src=\"");
      out.print(embedUrl);
      out.write("\" \r\n");
      out.write("							        title=\"Video de YouTube para ");
      out.print(edi.getNombre());
      out.write("\"\r\n");
      out.write("							        frameborder=\"0\" \r\n");
      out.write("							        allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" \r\n");
      out.write("							        referrerpolicy=\"strict-origin-when-cross-origin\"\r\n");
      out.write("							        allowfullscreen>\r\n");
      out.write("							</iframe>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				");

					}
				}
				
      out.write("\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<script\r\n");
      out.write("        src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
