/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.13
 * Generated at: 2025-12-06 07:52:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.pages;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.Set;
import java.util.Map;
import java.net.URLEncoder;
import webservices.DataUsuario;
import webservices.DtOrganizador;
import webservices.DtAsistente;

public final class detalleUsuario_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(8);
    _jspx_imports_classes.add("webservices.DataUsuario");
    _jspx_imports_classes.add("java.net.URLEncoder");
    _jspx_imports_classes.add("java.util.Map");
    _jspx_imports_classes.add("java.util.Set");
    _jspx_imports_classes.add("webservices.DtAsistente");
    _jspx_imports_classes.add("webservices.DtOrganizador");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("\r\n");
      out.write("<html lang=\"es\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\" />\r\n");
      out.write("<meta http-equiv=\"x-ua-compatible\" content=\"ie=edge\" />\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />\r\n");
      out.write("<title>Detalle de Usuario - Eventos.uy</title>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/boxicons@latest/css/boxicons.min.css\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://fonts.googleapis.com/css2?family=Titillium+Web:wght@300;400;600&display=swap\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/ConsultaEvento.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/styles.css\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"assets/css/RolVisitante_listarUsuarios.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://fonts.googleapis.com/css2?family=Inter&display=swap\" />\r\n");
      out.write("<link rel=\"icon\" type=\"image/x-icon\" href=\"assets/icons/Logo.png\">\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap Icons CDN -->\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write(":root {\r\n");
      out.write("	--bg: #f4f6f8;\r\n");
      out.write("	--surface: #ffffff;\r\n");
      out.write("	--text: #1f2937;\r\n");
      out.write("	--muted: #6b7280;\r\n");
      out.write("	--border: #e6e8eb;\r\n");
      out.write("	--accent: #6d5dfc;\r\n");
      out.write("	--accent-weak: #edeaff;\r\n");
      out.write("	--radius: 8px;\r\n");
      out.write("	--shadow: 0 6px 18px rgba(15, 23, 42, .06);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("body {\r\n");
      out.write("	background: var(--bg);\r\n");
      out.write("	color: var(--text);\r\n");
      out.write("	margin: 0;\r\n");
      out.write("	padding-left: var(--sidebar-w);\r\n");
      out.write("	transition: padding-left .2s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* main container spacing */\r\n");
      out.write("main.contUser {\r\n");
      out.write("	padding: 18px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".container-xl {\r\n");
      out.write("	max-width: 1200px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* card tweaks */\r\n");
      out.write(".card {\r\n");
      out.write("	border: 1px solid var(--border);\r\n");
      out.write("	border-radius: var(--radius);\r\n");
      out.write("	box-shadow: var(--shadow);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* avatar */\r\n");
      out.write(".avatar {\r\n");
      out.write("	width: 64px;\r\n");
      out.write("	height: 64px;\r\n");
      out.write("	border-radius: 50%;\r\n");
      out.write("	border: 2px solid var(--accent-weak);\r\n");
      out.write("	object-fit: cover;\r\n");
      out.write("	background: #fff;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* actions grid */\r\n");
      out.write(".action-card {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	gap: 12px;\r\n");
      out.write("	align-items: center;\r\n");
      out.write("	background: #fcfcff;\r\n");
      out.write("	border: 1px solid var(--border);\r\n");
      out.write("	border-radius: 10px;\r\n");
      out.write("	padding: 12px;\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("	color: inherit;\r\n");
      out.write("	transition: background .12s ease, transform .06s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".action-card:hover {\r\n");
      out.write("	background: #f6f7ff;\r\n");
      out.write("	border-color: #dfe3ff;\r\n");
      out.write("	transform: translateY(-1px);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* collapsed styles */\r\n");
      out.write("body.with-collapsed {\r\n");
      out.write("	padding-left: var(--sidebar-w-collapsed);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sidebar.collapsed .nav-text {\r\n");
      out.write("	display: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sidebar.collapsed .nav-link {\r\n");
      out.write("	justify-content: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sidebar.collapsed .nav-icon {\r\n");
      out.write("	margin-right: 0 !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* responsive */\r\n");
      out.write("@media ( max-width : 767.98px) {\r\n");
      out.write("	body {\r\n");
      out.write("		padding-left: var(--sidebar-w-collapsed);\r\n");
      out.write("	}\r\n");
      out.write("	.sidebar {\r\n");
      out.write("		width: var(--sidebar-w-collapsed);\r\n");
      out.write("	}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".action-card {\r\n");
      out.write("	min-width: 0;\r\n");
      out.write("}\r\n");
      out.write("/*.actions-grid .col-12 { display:flex; }*/\r\n");
      out.write(".action-card {\r\n");
      out.write("	width: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".row {\r\n");
      out.write("	display: flex !important;\r\n");
      out.write("	flex-wrap: nowrap !important; /* evita que salten de línea */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".row>[class*=\"col-\"] {\r\n");
      out.write("	flex: 0 0 auto; /* que respeten su ancho */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".contenedor-edicion { gap: 6px; align-items: center; }\r\n");
      out.write(".nombreEdicion { margin-left: 4px; }\r\n");
      out.write(".contenedor-fotoPerfil { margin-bottom: 8px; }\r\n");
      out.write(".contenedor-NickRolUser { margin-top: 4px; }\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../templates/header.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("	");

	DataUsuario usuario = (DataUsuario) request.getAttribute("usuario"); 
	if (usuario == null) {
        response.sendRedirect(request.getContextPath() + "/usuarios?accion=listar");
        return;
    }
	
	Object detalleObj = request.getAttribute("detalleUsuario");
	DtAsistente asis = null;
	DtOrganizador org = null;
	if (detalleObj instanceof DtOrganizador) {
		org = (DtOrganizador) detalleObj;
	} else if (detalleObj instanceof DtAsistente) {
		asis = (DtAsistente) detalleObj;
	}
	
	@SuppressWarnings("unchecked")
	Set<String> ediciones = (Set<String>) request.getAttribute("ediciones");
	@SuppressWarnings("unchecked")
	Map<String, String> edicionesMap = (Map<String, String>) request.getAttribute("edicionesMap");
	String imagenUsuario = (String) request.getAttribute("imagenUsuario");
	
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body id=\"body-pd\">\r\n");
      out.write("	\r\n");
      out.write("	<!-- Contenido -->\r\n");
      out.write("	<main class=\"contUser\" id=\"cuenta-user\">\r\n");
      out.write("		<div class=\"container-xl \">\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				<!--pa dejar dos cartas en una sola columna y la otra a su izq-->\r\n");
      out.write("				<div class=\"col-10 mb-3 mb-lg-0\">\r\n");
      out.write("\r\n");
      out.write("					<!-- Header perfil -->\r\n");
      out.write("					<section class=\"card mb-3 bg-light \">\r\n");
      out.write("						<!-- make card-body a centered flex container so inner row is centered horizontally and vertically -->\r\n");
      out.write("                        <div class=\"card-body align-items-center d-flex justify-content-between gap-4 \" style=\"min-height:180px;\">\r\n");
      out.write("							<div class=\"d-flex align-items-center justify-content-between gap-4 w-100\">\r\n");
      out.write("                                <div class=\"d-flex align-items-center gap-3 flex-wrap col-4\" id=\"fotoCarnet\">\r\n");
      out.write("                                    <div class=\"contenedor-fotoPerfil mb-0\">\r\n");
      out.write("                                        <img class=\"foto-usuario avatar\" src=\"");
      out.print( imagenUsuario );
      out.write("\"\r\n");
      out.write("                                            alt=\"");
      out.print( usuario.getNickname() );
      out.write("\" style=\"height: 127px; width:127px;\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"contenedor-NickRolUser text-start\">\r\n");
      out.write("                                        <div class=\"nickname\">\r\n");
      out.write("                                            <b>");
      out.print( usuario.getNickname() );
      out.write("</b>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"rol\">");
      out.print( usuario.getTipo() );
      out.write("</div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"d-flex flex-column contenedor-datosUsuario text-start col-4\" id=\"datos\">\r\n");
      out.write("                                     <div class=\"datosUsuario\">\r\n");
      out.write("                                        <div class=\"nombre\">\r\n");
      out.write("                                            <u>Nombre:</u> ");
      out.print( usuario.getNombre() );
      out.write("\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"email\">\r\n");
      out.write("                                            <u>Email:</u> ");
      out.print( usuario.getEmail() );
      out.write("\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        \r\n");
      out.write("                                        <!-- Contador de seguidores y seguidos -->\r\n");
      out.write("                                        <div class=\"seguidores-info mt-2\">\r\n");
      out.write("                                            <div class=\"seguidores\">\r\n");
      out.write("                                                <u>Seguidores:</u> <span id=\"cantidadSeguidores\">");
      out.print( request.getAttribute("cantidadSeguidores") != null ? request.getAttribute("cantidadSeguidores") : 0 );
      out.write("</span>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"seguidos\">\r\n");
      out.write("                                                <u>Siguiendo:</u> <span id=\"cantidadSeguidos\">");
      out.print( request.getAttribute("cantidadSeguidos") != null ? request.getAttribute("cantidadSeguidos") : 0 );
      out.write("</span>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        \r\n");
      out.write("                                        ");
 if (org != null) { 
      out.write("\r\n");
      out.write("                                            <div class=\"fechaNacimiento\">\r\n");
      out.write("                                                <u>Descripción:</u> ");
      out.print( org.getDescripcion() );
      out.write("\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"institucion\">\r\n");
      out.write("                                                <u>Web:</u> <a href=\"");
      out.print( org.getWeb() );
      out.write("\" target=\"_blank\">");
      out.print( org.getWeb() );
      out.write("</a>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        ");
 } else if (asis != null) {  
      out.write("\r\n");
      out.write("                                            <div class=\"fechaNacimiento\">\r\n");
      out.write("                                                <u>Fecha de Nacimiento:</u> ");
      out.print( asis.getFechaNacimiento() );
      out.write("\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"apellido\">\r\n");
      out.write("                                                <u>Apellido:</u> ");
      out.print( asis.getApellido() );
      out.write("\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        \r\n");
      out.write("                                            ");
 if (asis.getInstitucion() != null && !asis.getInstitucion().isBlank()) { 
      out.write("\r\n");
      out.write("                                                <div class=\"institucion\">\r\n");
      out.write("                                                    <u>Institución:</u> ");
      out.print( asis.getInstitucion() );
      out.write("\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            ");
 } 
      out.write("\r\n");
      out.write("                                        ");
 } 
      out.write("\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                \r\n");
      out.write("                                <!-- Botón de seguir/dejar de seguir -->\r\n");
      out.write("                                ");
 
                                String usuarioLogueado = (String) request.getAttribute("usuarioLogueado");
                                Boolean yaSigue = (Boolean) request.getAttribute("yaSigue");
                                if (usuarioLogueado != null && !usuarioLogueado.equals(usuario.getNickname())) { 
                                
      out.write("\r\n");
      out.write("                                <div class=\"d-flex flex-column justify-content-center col-3\" id=\"accionesSeguimiento\">\r\n");
      out.write("                                    ");
 if (yaSigue != null && yaSigue) { 
      out.write("\r\n");
      out.write("                                        <!-- Botón para dejar de seguir (cuando ya sigue) -->\r\n");
      out.write("                                        <form method=\"post\" action=\"");
      out.print( request.getContextPath() );
      out.write("/dejarDeSeguir\">\r\n");
      out.write("                                            <input type=\"hidden\" name=\"usuario\" value=\"");
      out.print( usuario.getNickname() );
      out.write("\">\r\n");
      out.write("                                            <button type=\"submit\" class=\"btn btn-outline-secondary w-100\">\r\n");
      out.write("                                                <i class=\"bi bi-person-dash\"></i> Dejar de seguir\r\n");
      out.write("                                            </button>\r\n");
      out.write("                                        </form>\r\n");
      out.write("                                    ");
 } else { 
      out.write("\r\n");
      out.write("                                        <!-- Botón para seguir (cuando no sigue) -->\r\n");
      out.write("                                        <form method=\"post\" action=\"");
      out.print( request.getContextPath() );
      out.write("/seguirUsuario\">\r\n");
      out.write("                                            <input type=\"hidden\" name=\"usuario\" value=\"");
      out.print( usuario.getNickname() );
      out.write("\">\r\n");
      out.write("                                            <button type=\"submit\" class=\"btn btn-primary w-100\">\r\n");
      out.write("                                                <i class=\"bi bi-person-plus\"></i> Seguir\r\n");
      out.write("                                            </button>\r\n");
      out.write("                                        </form>\r\n");
      out.write("                                    ");
 } 
      out.write("\r\n");
      out.write("                                    \r\n");
      out.write("                                    <!-- Mostrar mensajes de seguimiento -->\r\n");
      out.write("                                    ");
 
                                    String mensajeSeguimiento = (String) request.getAttribute("mensajeSeguimiento");
                                    String errorSeguimiento = (String) request.getAttribute("errorSeguimiento");
                                    if (mensajeSeguimiento != null) { 
                                    
      out.write("\r\n");
      out.write("                                        <div class=\"alert alert-success mt-2\" role=\"alert\">\r\n");
      out.write("                                            ");
      out.print( mensajeSeguimiento );
      out.write("\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    ");
 } 
      out.write("\r\n");
      out.write("                                    ");
 if (errorSeguimiento != null) { 
      out.write("\r\n");
      out.write("                                        <div class=\"alert alert-danger mt-2\" role=\"alert\">\r\n");
      out.write("                                            ");
      out.print( errorSeguimiento );
      out.write("\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    ");
 } 
      out.write("\r\n");
      out.write("                                </div>\r\n");
      out.write("                                ");
 } 
      out.write("\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </section>\r\n");
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("				\r\n");
      out.write("			</div>\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("			");
 if (org != null) { 
      out.write("\r\n");
      out.write("			<div class=\"container-xl mt-3\">\r\n");
      out.write("				<section class=\"card p-3\">\r\n");
      out.write("					<h5>Ediciones organizadas:</h5>\r\n");
      out.write("					<div class=\"d-flex flex-column mt-2\">\r\n");
      out.write("						");
 if (ediciones != null && !ediciones.isEmpty()) {
                            for (String ed : ediciones) {
                                String imgEd = (edicionesMap != null) ? edicionesMap.get(ed) : null;
                        
      out.write("\r\n");
      out.write("                                <div class=\"contenedor-edicion d-flex align-items-center gap-2 mb-2\">\r\n");
      out.write("                                    <a href=\"");
      out.print( request.getContextPath() );
      out.write("/detalleEdicion?nombre=");
      out.print( URLEncoder.encode(ed, "UTF-8") );
      out.write("\" style=\"display:inline-block;width:64px;height:64px;\">\r\n");
      out.write("                                        <img class=\"foto-edicion\" src=\"");
      out.print(imgEd);
      out.write("\" alt=\"edicion\" style=\"width:64px;height:64px;object-fit:cover;display:inline-block;vertical-align:middle;\">\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                    <div class=\"nombreEdicion\" style=\"margin-left:6px;\">\r\n");
      out.write("                                        <a href=\"");
      out.print( request.getContextPath() );
      out.write("/detalleEdicion?nombre=");
      out.print( URLEncoder.encode(ed, "UTF-8") );
      out.write("\" class=\"text-decoration-none\"><b>");
      out.print( ed );
      out.write("</b></a>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                  \r\n");
      out.write("                                </div>\r\n");
      out.write("                            ");
 }
                        } else { 
      out.write("\r\n");
      out.write("							<div class=\"text-muted\">No tiene ediciones organizadas.</div>\r\n");
      out.write("						");
 } 
      out.write("\r\n");
      out.write("					</div>\r\n");
      out.write("				</section>\r\n");
      out.write("			</div>\r\n");
      out.write("			");
 } 
      out.write("\r\n");
      out.write("			\r\n");
      out.write("		</main>\r\n");
      out.write("\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
