/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.13
 * Generated at: 2025-12-06 21:14:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.pages;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import webservices.*;
import java.util.List;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("webservices");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("java.util.List");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"es\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Eventos.uy</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/styles.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/index.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css2?family=Inter&display=swap\"/>\r\n");
      out.write("    <link rel=\"icon\" type=\"image/x-icon\" href=\"assets/icons/Logo.png\">    <!-- Icono de la pestaña -->\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB\" crossorigin=\"anonymous\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.css\">\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-FKyoEForCGlyvwx9Hj09JcYn3nv7wiPVlz7YYwJrWVcXK/BmnVDxM+D2scQbITxI\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../templates/header.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div class=\"hero-actions\">\r\n");
      out.write("        <div class=\"text-content-title\">\r\n");
      out.write("            <b class=\"title\">Eventos.uy</b>\r\n");
      out.write("            <div class=\"subtitle\">Donde tus ideas se vuelven experiencias.</div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <img class=\"section-icon\" alt=\"\" src=\"assets/images/section-image.jpg\">\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"row row-cols-1 row-cols-md-3 justify-content-center mt-4 dflex mx-1\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"carta-categorias align-items-center col-12 col-md-8 col-xl-3 h-100 my-3\">\r\n");
      out.write("            <h3 class=\"categorias fw-bold\">Categorías</h3>\r\n");
      out.write("            ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../templates/categorias-sidebar.jsp", out, false);
      out.write("\r\n");
      out.write("            <div class=\"d-flex justify-content-center mt-3\">\r\n");
      out.write("                <a href=\"");
      out.print( request.getContextPath() );
      out.write("/listarUsuarios\"\r\n");
      out.write("                   class=\"btn btn-dark rounded-pill px-4 py-2 d-flex align-items-center gap-2 text-white\"\r\n");
      out.write("                   style=\"font-weight: 500;\"> \r\n");
      out.write("                    <i class=\"bi bi-people\" style=\"font-size: 1.2rem; color: #fff;\"></i>\r\n");
      out.write("                    <span class=\"text-white\">Usuarios</span>\r\n");
      out.write("                </a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"col-12 col-md-8 mb-3\">\r\n");
      out.write("	<h3 class=\"d-flex justify-content-center fw-bold my-3\">Eventos Recientes</h3>\r\n");
      out.write("   <div class=\"row m-2\">\r\n");
      out.write("   		\r\n");
      out.write("            <div class=\"row gx-0 g-xl-2 gy-2\">\r\n");
      out.write("                \r\n");
      out.write("			");
 
			List<DtDetalleEvento> eventos = (List<DtDetalleEvento>) request.getAttribute("eventos_recientes");
			if (eventos == null || eventos.isEmpty()) { 
      out.write("\r\n");
      out.write("				<div class=\"alert alert-light\" role=\"alert\">No hay eventos recientes disponibles.</div> ");
 }
			for (DtDetalleEvento evento : eventos) { 
      out.write("\r\n");
      out.write("				<div class=\"col-xl-6\">\r\n");
      out.write("				<a class=\"text-decoration-none\" href=\"detalleEvento?nombre=");
      out.print( evento.getNombre() );
      out.write("\"\r\n");
      out.write("					data-hotkey=\"5\" role=\"button\">\r\n");
      out.write("					<div class=\"carta p-4\">\r\n");
      out.write("						<div class=\"text-heading\">\r\n");
      out.write("							<div class=\"search-text-heading\">");
      out.print( evento.getNombre() );
      out.write("</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"avatar-block\">\r\n");
      out.write("							<div class=\"avatar\">\r\n");
      out.write("								<img class=\"shape-icon\" alt=\"\"\r\n");
      out.write("									src=\"");
      out.print( request.getAttribute(evento.getNombre()) );
      out.write("\">\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"info\">\r\n");
      out.write("								<div class=\"description\"> ");
      out.print( evento.getDescripcion() );
      out.write(" </div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</a>\r\n");
      out.write("			</div>\r\n");
      out.write("			");

			}
			
			
      out.write("\r\n");
      out.write("\r\n");
      out.write("                \r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("   <div class=\"modal fade\" id=\"mensajeModal\" tabindex=\"-1\" aria-labelledby=\"mensajeModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("    <div class=\"modal-dialog modal-dialog-centered\">\r\n");
      out.write("        <div class=\"modal-content\">\r\n");
      out.write("            <div class=\"modal-header\" style=\"display: flex !important; width: 100% !important;\">\r\n");
      out.write("			    <h5 class=\"modal-title\" id=\"mensajeModalLabel\" style=\"flex-grow: 1 !important; margin: 0 !important;\">Mensaje</h5>\r\n");
      out.write("			    <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Close\" style=\"flex-shrink: 0 !important; margin-left: auto !important;\"></button>\r\n");
      out.write("			</div>\r\n");
      out.write("            <div class=\"modal-body\" id=\"mensajeModalBody\"></div>\r\n");
      out.write("            <div class=\"modal-footer\">\r\n");
      out.write("                <button type=\"button\" class=\"btn btn-secondary\" data-bs-dismiss=\"modal\">Cerrar</button>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("     </div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<script src=\"assets/js/main.js\"></script>\r\n");
      out.write("	<script>\r\n");
      out.write("	    (function() {\r\n");
      out.write("	        var mensaje = '");
      out.print( request.getAttribute("mensaje") );
      out.write("';\r\n");
      out.write("	        if (mensaje && mensaje.length > 0 && mensaje !== 'null') {\r\n");
      out.write("	            var body = document.getElementById('mensajeModalBody');\r\n");
      out.write("	            if (body) body.textContent = mensaje;\r\n");
      out.write("	            var modalEl = document.getElementById('mensajeModal');\r\n");
      out.write("	            if (modalEl) {\r\n");
      out.write("	                var modal = new bootstrap.Modal(modalEl);\r\n");
      out.write("	                modal.show();\r\n");
      out.write("	            } else {\r\n");
      out.write("	                alert(mensaje);\r\n");
      out.write("	            }\r\n");
      out.write("	        }\r\n");
      out.write("	    })();\r\n");
      out.write("	</script>\r\n");
      out.write("	\r\n");
      out.write("	</body>\r\n");
      out.write("</html>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
