/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.13
 * Generated at: 2025-12-06 07:51:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.pages;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.Set;
import java.util.Map;
import java.net.URLEncoder;
import webservices.DataUsuario;

public final class listarUsuarios_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(6);
    _jspx_imports_classes.add("webservices.DataUsuario");
    _jspx_imports_classes.add("java.net.URLEncoder");
    _jspx_imports_classes.add("java.util.Map");
    _jspx_imports_classes.add("java.util.Set");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("\r\n");
  @SuppressWarnings("unchecked")
    DataUsuario usuariO = (DataUsuario) request.getAttribute("usuario");
    
    @SuppressWarnings("unchecked")
    Set<DataUsuario> usuarios = (Set<DataUsuario>) request.getAttribute("usuarios");
    if (usuarios == null) usuarios = java.util.Collections.emptySet();

    @SuppressWarnings("unchecked")
    Map<String,String> imgsUsuarios = (Map<String,String>) request.getAttribute("imgsUsuarios");
    if (imgsUsuarios == null) imgsUsuarios = java.util.Collections.emptyMap();

    @SuppressWarnings("unchecked")
    Map<String,Boolean> estadosSeguimiento = (Map<String,Boolean>) request.getAttribute("estadosSeguimiento");
    if (estadosSeguimiento == null) estadosSeguimiento = java.util.Collections.emptyMap();

    String usuarioLogueado = (String) request.getAttribute("usuarioLogueado");
    String q = (String) request.getAttribute("q");
    if (q == null) q = "";

    String ctx = request.getContextPath();

      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("	<head>\r\n");
      out.write("		<meta charset=\"UTF-8\">\r\n");
      out.write("		<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("		<title>Listar usuarios</title>\r\n");
      out.write("		<link rel=\"stylesheet\" href=\"");
      out.print( ctx );
      out.write("/assets/css/styles.css\">\r\n");
      out.write("		<link rel=\"stylesheet\"\r\n");
      out.write("			href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css\">\r\n");
      out.write("		<link rel=\"stylesheet\"\r\n");
      out.write("			href=\"");
      out.print( ctx );
      out.write("/assets/css/RolVisitante_listarUsuarios.css\">\r\n");
      out.write("		<link rel=\"stylesheet\"\r\n");
      out.write("			href=\"https://fonts.googleapis.com/css2?family=Inter&display=swap\" />\r\n");
      out.write("		<!-- Bootstrap Icons CDN -->\r\n");
      out.write("		<link\r\n");
      out.write("			href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css\"\r\n");
      out.write("			rel=\"stylesheet\">\r\n");
      out.write("		<link rel=\"icon\" type=\"image/x-icon\" href=\"");
      out.print( ctx );
      out.write("/assets/icons/Logo.png\">\r\n");
      out.write("		\r\n");
      out.write("		<style>\r\n");
      out.write("			.card {\r\n");
      out.write("				overflow: hidden;\r\n");
      out.write("				box-shadow: 0 2px 4px rgba(0,0,0,0.1);\r\n");
      out.write("			}\r\n");
      out.write("			\r\n");
      out.write("			.user.row {\r\n");
      out.write("				margin: 0;\r\n");
      out.write("				width: 100%;\r\n");
      out.write("			}\r\n");
      out.write("			\r\n");
      out.write("			.user .col-auto:first-child {\r\n");
      out.write("				padding-right: 0;\r\n");
      out.write("			}\r\n");
      out.write("			\r\n");
      out.write("			.user .col {\r\n");
      out.write("				padding-left: 0;\r\n");
      out.write("				padding-right: 0;\r\n");
      out.write("			}\r\n");
      out.write("			\r\n");
      out.write("			.user .col-auto:last-child {\r\n");
      out.write("				padding-left: 0;\r\n");
      out.write("				padding-right: 20px;\r\n");
      out.write("			}\r\n");
      out.write("			\r\n");
      out.write("			.user-actions {\r\n");
      out.write("				display: flex;\r\n");
      out.write("				align-items: center;\r\n");
      out.write("				justify-content: flex-end;\r\n");
      out.write("			}\r\n");
      out.write("			\r\n");
      out.write("			.btn-seguir {\r\n");
      out.write("				white-space: nowrap;\r\n");
      out.write("				font-size: 0.875rem;\r\n");
      out.write("				padding: 0.375rem 0.75rem;\r\n");
      out.write("			}\r\n");
      out.write("			\r\n");
      out.write("			/* Para pantallas más pequeñas */\r\n");
      out.write("			@media (max-width: 768px) {\r\n");
      out.write("				.btn-seguir {\r\n");
      out.write("					font-size: 0.75rem;\r\n");
      out.write("					padding: 0.25rem 0.5rem;\r\n");
      out.write("				}\r\n");
      out.write("				\r\n");
      out.write("				.user .col-auto:last-child {\r\n");
      out.write("					padding-right: 15px;\r\n");
      out.write("				}\r\n");
      out.write("			}\r\n");
      out.write("			\r\n");
      out.write("			@media (max-width: 576px) {\r\n");
      out.write("				.btn-seguir {\r\n");
      out.write("					font-size: 0.7rem;\r\n");
      out.write("					padding: 0.2rem 0.4rem;\r\n");
      out.write("				}\r\n");
      out.write("				\r\n");
      out.write("				.user .col-auto:last-child {\r\n");
      out.write("					padding-right: 10px;\r\n");
      out.write("				}\r\n");
      out.write("			}\r\n");
      out.write("		</style>\r\n");
      out.write("	</head>\r\n");
      out.write("	\r\n");
      out.write("	<body>\r\n");
      out.write("\r\n");
      out.write("		");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../templates/header.jsp", out, false);
      out.write("\r\n");
      out.write("	\r\n");
      out.write("		<main class=\"container my-5\">\r\n");
      out.write("			<div class=\"row justify-content-center mb-4 align-items-center\">\r\n");
      out.write("				<div class=\"col-md-6\">\r\n");
      out.write("					<form method=\"get\" action=\"");
      out.print( ctx );
      out.write("/listarUsuarios\" role=\"search\">\r\n");
      out.write("						<div class=\"input-group rounded-pill overflow-hidden shadow-sm\">\r\n");
      out.write("							<!-- Only show the search input; submit on Enter. -->\r\n");
      out.write("							<input type=\"search\" name=\"q\" class=\"form-control form-control-lg border-0\"\r\n");
      out.write("								placeholder=\"Buscar usuarios registrados\"\r\n");
      out.write("								value=\"");
      out.print( q );
      out.write("\" aria-label=\"Buscar usuarios\"\r\n");
      out.write("								onkeydown=\"if(event.key === 'Enter'){ this.form.submit(); }\">\r\n");
      out.write("						</div>\r\n");
      out.write("					</form>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div id=\"listar\" class=\"row justify-content-center\">\r\n");
      out.write("				<div class=\"col-md-8\">\r\n");
      out.write("					");
 if (usuarios.isEmpty()) { 
      out.write("\r\n");
      out.write("						<div class=\"alert alert-info text-center\">\r\n");
      out.write("							<i class=\"bi bi-info-circle\"></i>\r\n");
      out.write("							No se encontraron usuarios.\r\n");
      out.write("						</div>\r\n");
      out.write("					");
 } else {
						for (DataUsuario usuario : usuarios) {
							String nick = usuario.getNickname();
							String imgRel = imgsUsuarios.get(nick);
							if (imgRel == null || imgRel.isBlank()) imgRel = "uploads/usuarios/default.jpg";
							String detalleUrl = ctx + "/detalleUsuario?usuarios=" + URLEncoder.encode(nick, "UTF-8");
							Boolean seguido = estadosSeguimiento.get(nick);
							Boolean esUsuarioLogueado = usuarioLogueado != null && nick.equals(usuarioLogueado);
						
      out.write("\r\n");
      out.write("							<div class=\"card rounded-5 mb-3\">\r\n");
      out.write("								<div class=\"user row g-0 align-items-center\">\r\n");
      out.write("									<div class=\"col-auto\">\r\n");
      out.write("										<a href=\"");
      out.print( detalleUrl );
      out.write("\" class=\"text-decoration-none\">\r\n");
      out.write("											<img src=\"");
      out.print( imgRel );
      out.write("\" alt=\"");
      out.print( nick );
      out.write("\"\r\n");
      out.write("											class=\"img-fluid rounded-circle m-3\"\r\n");
      out.write("											style=\"width: 90px; height: 90px; object-fit: cover;\">\r\n");
      out.write("										</a>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div class=\"col user-card-content\">\r\n");
      out.write("										<a href=\"");
      out.print( detalleUrl );
      out.write("\" class=\"text-decoration-none\">\r\n");
      out.write("											<div class=\"card-body\">\r\n");
      out.write("												<h5 class=\"card-title mb-1 text-dark\">");
      out.print( nick );
      out.write("</h5>\r\n");
      out.write("												<p class=\"card-text text-secondary mb-0\">");
      out.print( usuario.getTipo() );
      out.write("</p>\r\n");
      out.write("											</div>\r\n");
      out.write("										</a>\r\n");
      out.write("									</div>\r\n");
      out.write("									");
 if (usuarioLogueado != null && !esUsuarioLogueado) { 
      out.write("\r\n");
      out.write("									<div class=\"col-auto user-actions\">\r\n");
      out.write("										");
 if (seguido != null && seguido) { 
      out.write("\r\n");
      out.write("											<!-- Botón para dejar de seguir -->\r\n");
      out.write("											<form action=\"");
      out.print( ctx );
      out.write("/dejarDeSeguir\" method=\"post\" class=\"d-inline\" \r\n");
      out.write("												  onclick=\"event.stopPropagation();\">\r\n");
      out.write("												<input type=\"hidden\" name=\"usuario\" value=\"");
      out.print( nick );
      out.write("\">\r\n");
      out.write("												<button type=\"submit\" class=\"btn btn-outline-secondary btn-seguir\">\r\n");
      out.write("													<i class=\"bi bi-person-dash\"></i> Dejar de seguir\r\n");
      out.write("												</button>\r\n");
      out.write("											</form>\r\n");
      out.write("										");
 } else { 
      out.write("\r\n");
      out.write("											<!-- Botón para seguir -->\r\n");
      out.write("											<form action=\"");
      out.print( ctx );
      out.write("/seguirUsuario\" method=\"post\" class=\"d-inline\" \r\n");
      out.write("												  onclick=\"event.stopPropagation();\">\r\n");
      out.write("												<input type=\"hidden\" name=\"usuario\" value=\"");
      out.print( nick );
      out.write("\">\r\n");
      out.write("												<button type=\"submit\" class=\"btn btn-primary btn-seguir\">\r\n");
      out.write("													<i class=\"bi bi-person-plus\"></i> Seguir\r\n");
      out.write("												</button>\r\n");
      out.write("											</form>\r\n");
      out.write("										");
 } 
      out.write("\r\n");
      out.write("									</div>\r\n");
      out.write("									");
 } 
      out.write("\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						");
 }
						} 
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</main>\r\n");
      out.write("		\r\n");
      out.write("		<script\r\n");
      out.write("			src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("	</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
