/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.13
 * Generated at: 2025-12-05 18:42:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.pages;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.Set;
import java.util.Map;
import webservices.*;

public final class listarEventos_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("webservices");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(3);
    _jspx_imports_classes.add("java.util.Map");
    _jspx_imports_classes.add("java.util.Set");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

    @SuppressWarnings("unchecked")
    Set<String> eventos = (Set<String>) request.getAttribute("eventos");
    @SuppressWarnings("unchecked")
    Set<Map<String, Object>> eventosInfo = (Set<Map<String, Object>>) request.getAttribute("eventosInfo");
    @SuppressWarnings("unchecked")
    Set<String> categorias = (Set<String>) request.getAttribute("categorias");
    String categoriaSeleccionada = (String) request.getAttribute("categoriaSeleccionada");
    String nombreBusqueda = (String) request.getAttribute("nombreBusqueda");
    String tipoFiltro = (String) request.getAttribute("tipoFiltro");
    String ordenamiento = (String) request.getAttribute("ordenamiento");
    Integer totalEventos = (Integer) request.getAttribute("totalEventos");
    Integer totalEdiciones = (Integer) request.getAttribute("totalEdiciones");
    Integer eventosFiltrados = (Integer) request.getAttribute("eventosFiltrados");
    
    // Obtener información del usuario de la sesión
    DataUsuario usuario = (DataUsuario) request.getSession().getAttribute("usuario");

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"es\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<title>Buscar eventos/ediciones - Eventos.uy</title>\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://fonts.googleapis.com/css2?family=Inter&display=swap\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/assets/css/styles.css\">\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css\"\r\n");
      out.write("	rel=\"stylesheet\"\r\n");
      out.write("	integrity=\"sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB\"\r\n");
      out.write("	crossorigin=\"anonymous\">\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js\"\r\n");
      out.write("	integrity=\"sha384-FKyoEForCGlyvwx9Hj09JcYn3nv7wiPVlz7YYwJrWVcXK/BmnVDxM+D2scQbITxI\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write("<link rel=\"icon\" type=\"image/x-icon\" href=\"");
      out.print(request.getContextPath());
      out.write("/assets/icons/Logo.png\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../templates/header.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("		<div class=\"m-4\">\r\n");
      out.write("			<h2 class=\"fw-bold my-3\">Buscar eventos/ediciones</h2>\r\n");
      out.write("			\r\n");
      out.write("			<div class=\"row row-cols-2 w-100 justify-content-center my-4 gap-5\">\r\n");
      out.write("				<div class=\"align-items-center col-12 col-xl-3 my-3\">\r\n");
      out.write("					<h3 class=\"categorías fw-bold text-center\">Categorías</h3>\r\n");
      out.write("					");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../templates/categorias-sidebar.jsp", out, false);
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"row container m-2 col-12 col-xl-8 h-100\">\r\n");
      out.write("\r\n");
      out.write("					<!-- Mostrar información de filtros -->\r\n");
      out.write("					");
if (eventosFiltrados != null) { 
      out.write("\r\n");
      out.write("						<div class=\"col-12 mb-3\">\r\n");
      out.write("							<div class=\"d-flex flex-wrap align-items-center gap-2 mb-2\">\r\n");
      out.write("								<span class=\"text-muted\">\r\n");
      out.write("									");
      out.print(eventosFiltrados);
      out.write(" resultado(s)\r\n");
      out.write("									");
if (totalEventos != null && totalEdiciones != null) { 
      out.write("\r\n");
      out.write("										(");
      out.print(totalEventos + totalEdiciones);
      out.write(" total)\r\n");
      out.write("									");
} 
      out.write("\r\n");
      out.write("								</span>\r\n");
      out.write("								");
if (tipoFiltro != null && !tipoFiltro.isEmpty()) { 
      out.write("\r\n");
      out.write("									<span class=\"badge bg-primary\">");
      out.print("eventos".equals(tipoFiltro) ? "Eventos" : "Ediciones");
      out.write("</span>\r\n");
      out.write("								");
} 
      out.write("\r\n");
      out.write("								");
if (categoriaSeleccionada != null && !categoriaSeleccionada.isEmpty() && !"todas".equals(categoriaSeleccionada)) { 
      out.write("\r\n");
      out.write("									<span class=\"badge bg-secondary\">");
      out.print(categoriaSeleccionada);
      out.write("</span>\r\n");
      out.write("								");
} 
      out.write("\r\n");
      out.write("								");
if (nombreBusqueda != null && !nombreBusqueda.isEmpty()) { 
      out.write("\r\n");
      out.write("									<span class=\"badge bg-info\">\"");
      out.print(nombreBusqueda);
      out.write("\"</span>\r\n");
      out.write("								");
} 
      out.write("\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					");
} 
      out.write("\r\n");
      out.write("\r\n");
      out.write("					<div class=\"row row-cols-1 gx-0 gy-3 col-12 mt-0 gap-3\">\r\n");
      out.write("						");

						if (eventosInfo == null || eventosInfo.isEmpty()) {
						
      out.write("\r\n");
      out.write("							<div class=\"col-12\">\r\n");
      out.write("								<div class=\"alert alert-info text-center\">\r\n");
      out.write("									<i class=\"bi bi-info-circle\"></i>\r\n");
      out.write("									No se encontraron eventos o ediciones que coincidan con los criterios de búsqueda.\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						");

						} else {
							for (Map<String, Object> itemInfo : eventosInfo) {
								String nombreItem = (String) itemInfo.get("nombre");
								String descripcionItem = (String) itemInfo.get("descripcion");
								String imagenItem = (String) itemInfo.get("imagenEvento");
								String tipoItem = (String) itemInfo.get("tipo");
								String eventoParent = (String) itemInfo.get("eventoParent");
								
								// Determinar el enlace de destino
								String enlaceDestino;
								if ("evento".equals(tipoItem)) {
									enlaceDestino = request.getContextPath() + "/detalleEvento?nombre=" + java.net.URLEncoder.encode(nombreItem, "UTF-8");
								} else {
									enlaceDestino = request.getContextPath() + "/detalleEdicion?nombre=" + java.net.URLEncoder.encode(nombreItem, "UTF-8");
								}
						
      out.write("\r\n");
      out.write("							<!-- Card dinámico para evento o edición -->\r\n");
      out.write("							<div class=\"col m-0\">\r\n");
      out.write("								<a href=\"");
      out.print(enlaceDestino);
      out.write("\" class=\"text-decoration-none text-dark\">\r\n");
      out.write("									<div class=\"carta p-4\">\r\n");
      out.write("										<div class=\"d-flex justify-content-between align-items-start mb-2\">\r\n");
      out.write("											<div class=\"text-heading flex-grow-1\">\r\n");
      out.write("												<div class=\"search-text-heading\">");
      out.print(nombreItem);
      out.write("</div>\r\n");
      out.write("											</div>\r\n");
      out.write("											<div class=\"ms-2\">\r\n");
      out.write("												");
if ("evento".equals(tipoItem)) { 
      out.write("\r\n");
      out.write("													<span class=\"badge bg-success\">\r\n");
      out.write("														<i class=\"bi bi-calendar-event\"></i> Evento\r\n");
      out.write("													</span>\r\n");
      out.write("												");
} else { 
      out.write("\r\n");
      out.write("													<span class=\"badge bg-primary\">\r\n");
      out.write("														<i class=\"bi bi-geo-alt\"></i> Edición\r\n");
      out.write("													</span>\r\n");
      out.write("												");
} 
      out.write("\r\n");
      out.write("											</div>\r\n");
      out.write("										</div>\r\n");
      out.write("										<div class=\"d-flex flex-row justify-content-between align-items-start w-100\">\r\n");
      out.write("											<div class=\"avatar-block\">\r\n");
      out.write("												<div class=\"avatar\">\r\n");
      out.write("													<img class=\"shape-icon\" alt=\"Imagen de ");
      out.print(nombreItem);
      out.write("\"\r\n");
      out.write("														src=\"");
      out.print(imagenItem);
      out.write("\"\r\n");
      out.write("														onerror=\"this.onerror=null;this.src='");
      out.print(request.getContextPath());
      out.write("/assets/images/no-photo-or-blank-image-icon-loading-images-or-missing-image-mark-image-not-available-or-image-coming-soon-sign-simple-nature-silhouette-in-frame-isolated-illustration-vector.jpg'\">\r\n");
      out.write("												</div>\r\n");
      out.write("												<div class=\"info gap-1\">\r\n");
      out.write("													");
if (descripcionItem != null && !descripcionItem.trim().isEmpty()) { 
      out.write("\r\n");
      out.write("														<div class=\"d-flex align-items-center\">\r\n");
      out.write("															<i class=\"bi bi-info-circle mx-2\"></i>\r\n");
      out.write("															<div class=\"description\">");
      out.print(descripcionItem.length() > 150 ? descripcionItem.substring(0, 150) + "..." : descripcionItem);
      out.write("</div>\r\n");
      out.write("														</div>\r\n");
      out.write("													");
} 
      out.write("\r\n");
      out.write("													");
if ("edicion".equals(tipoItem) && eventoParent != null) { 
      out.write("\r\n");
      out.write("														<div class=\"d-flex align-items-center mt-1\">\r\n");
      out.write("															<i class=\"bi bi-arrow-up-right mx-2 text-muted\"></i>\r\n");
      out.write("															<small class=\"text-muted\">Evento: ");
      out.print(eventoParent);
      out.write("</small>\r\n");
      out.write("														</div>\r\n");
      out.write("													");
} 
      out.write("\r\n");
      out.write("												</div>\r\n");
      out.write("											</div>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("								</a>\r\n");
      out.write("							</div>\r\n");
      out.write("						");

							}
						}
						
      out.write("\r\n");
      out.write("\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<script src=\"");
      out.print(request.getContextPath());
      out.write("/assets/js/main.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
