/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.13
 * Generated at: 2025-12-06 07:32:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.pages;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.net.URLEncoder;
import webservices.DataUsuario;
import webservices.DtOrganizador;
import webservices.DtAsistente;

public final class perfil_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(6);
    _jspx_imports_classes.add("webservices.DataUsuario");
    _jspx_imports_classes.add("java.net.URLEncoder");
    _jspx_imports_classes.add("webservices.DtAsistente");
    _jspx_imports_classes.add("webservices.DtOrganizador");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html lang=\"es\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\" />\r\n");
      out.write("<meta http-equiv=\"x-ua-compatible\" content=\"ie=edge\" />\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />\r\n");
      out.write("<title>MiPerfil - Eventos.uy</title>\r\n");
      out.write("\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/boxicons@latest/css/boxicons.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Titillium+Web:wght@300;400;600&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/ConsultaEvento.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/styles.css\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/assets/css/RolVisitante_listarUsuarios.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css2?family=Inter&display=swap\" />\r\n");
      out.write("<link rel=\"icon\" type=\"image/x-icon\" href=\"");
      out.print(request.getContextPath());
      out.write("/assets/icons/Logo.png\">\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write(":root {\r\n");
      out.write("	--bg: #f4f6f8;\r\n");
      out.write("	--surface: #ffffff;\r\n");
      out.write("	--text: #1f2937;\r\n");
      out.write("	--muted: #6b7280;\r\n");
      out.write("	--border: #e6e8eb;\r\n");
      out.write("	--accent: #6d5dfc;\r\n");
      out.write("	--accent-weak: #edeaff;\r\n");
      out.write("	--radius: 8px;\r\n");
      out.write("	--shadow: 0 6px 18px rgba(15, 23, 42, .06);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("body {\r\n");
      out.write("	font-family: system-ui, -apple-system, \"Segoe UI\", Roboto, \"Titillium Web\", Arial, sans-serif;\r\n");
      out.write("	background: var(--bg);\r\n");
      out.write("	color: var(--text);\r\n");
      out.write("	margin: 0;\r\n");
      out.write("	padding-left: var(--sidebar-w);\r\n");
      out.write("	transition: padding-left .2s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* main container spacing */\r\n");
      out.write("main.contUser { padding: 18px; }\r\n");
      out.write(".container-xl { max-width: 1200px; }\r\n");
      out.write(".card { border: 1px solid var(--border); border-radius: var(--radius); box-shadow: var(--shadow); }\r\n");
      out.write(".avatar { width: 127px; height: 127px; border-radius: 50%; object-fit: cover; background: #fff; }\r\n");
      out.write(".action-card { display: flex; gap: 12px; align-items: center; background: #fcfcff; border: 1px solid var(--border); border-radius: 10px; padding: 12px; text-decoration: none; color: inherit; transition: background .12s ease, transform .06s ease; }\r\n");
      out.write(".action-card:hover { background: #f6f7ff; border-color: #dfe3ff; transform: translateY(-1px); }\r\n");
      out.write("\r\n");
      out.write("body.with-collapsed { padding-left: var(--sidebar-w-collapsed); }\r\n");
      out.write("@media ( max-width : 767.98px) { body { padding-left: var(--sidebar-w-collapsed); } .avatar { width: 96px; height: 96px; } .col-md-5, .col-md-7 { flex: 0 0 100%; max-width:100%; } }\r\n");
      out.write("\r\n");
      out.write(".text-muted.small { font-size: .85rem; }\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../templates/header.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("	");

	Object uObj = request.getAttribute("usuario");
	if (uObj == null) {
		// If not set, try session user (defensive)
		DataUsuario su = (DataUsuario) request.getSession().getAttribute("usuario");
		if (su == null) {
			response.sendRedirect(request.getContextPath() + "/login");
			return;
		}
		uObj = su;
	}

	DtOrganizador org = null;
	DtAsistente asis = null;
	String nickname = null;
	String nombre = null;
	String apellido = null;
	String email = null;
	String descripcion = null;
	String web = null;
	
	if (uObj instanceof DtOrganizador) {
		org = (DtOrganizador) uObj;
		nickname = org.getNickname();
		nombre = org.getNombre();
		email = org.getEmail();
		descripcion = org.getDescripcion();
		web = org.getWeb();
	} else if (uObj instanceof DtAsistente) {
		asis = (DtAsistente) uObj;
		nickname = asis.getNickname();
		nombre = asis.getNombre();
		apellido = asis.getApellido();
		email = asis.getEmail();
	}

	

	String encodedNick = URLEncoder.encode(nickname == null ? "" : nickname, "UTF-8");
	
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body id=\"body-pd\">\r\n");
      out.write("\r\n");
      out.write("	<main class=\"contUser\" id=\"mi-cuenta-user\">\r\n");
      out.write("		<div class=\"container-xl\">\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				<div class=\"col-12 col-md-6 mb-3 mb-lg-0\">\r\n");
      out.write("					<section class=\"card mb-3 bg-light\">\r\n");
      out.write("						<div class=\"card-body\">\r\n");
      out.write("							<div class=\"d-flex align-items-center justify-content-between gap-4\">\r\n");
      out.write("								<div class=\"d-flex flex-column align-items-center\">\r\n");
      out.write("									<div class=\"contenedor-fotoPerfil mb-2\">\r\n");
      out.write("										<img class=\"foto-usuario\" src=\"");
      out.print(request.getAttribute("imagenUsuario"));
      out.write("\" alt=\"fotoPerfil\" style=\"height:127px;\">\r\n");
      out.write("									</div>\r\n");
      out.write("									<div class=\"contenedor-NickRolUser text-center\">\r\n");
      out.write("										<div class=\"nickname\"><b>");
      out.print( nickname );
      out.write("</b></div>\r\n");
      out.write("										<div class=\"rol\">");
      out.print( (org!=null) ? "Organizador" : "Asistente" );
      out.write("</div>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"d-flex flex-column contenedor-datosUsuario\">\r\n");
      out.write("									<div class=\"datosUsuario\">\r\n");
      out.write("										<div class=\"nombre\"><u>Nombre:</u> ");
      out.print( nombre );
      out.write("</div>\r\n");
      out.write("										");
 if (asis != null) { 
      out.write("\r\n");
      out.write("											<div class=\"apellido\"><u>Apellido:</u> ");
      out.print( apellido );
      out.write("</div>\r\n");
      out.write("										");
 } 
      out.write("\r\n");
      out.write("										<div class=\"email\"><u>Email:</u> ");
      out.print( email );
      out.write("</div>\r\n");
      out.write("										");
 if (org != null) { 
      out.write("\r\n");
      out.write("											<div class=\"fechaNacimiento\"><u>Descripción:</u> ");
      out.print( descripcion );
      out.write("</div>\r\n");
      out.write("											<div class=\"institucion\"><u>Web:</u> <a href=\"");
      out.print( web );
      out.write("\" target=\"_blank\">");
      out.print( web );
      out.write("</a></div>\r\n");
      out.write("										");
 } else { 
      out.write("\r\n");
      out.write("											<div class=\"fechaNacimiento\"><u>Fecha de Nacimiento:</u> ");
      out.print( asis.getFechaNacimiento() );
      out.write("</div>\r\n");
      out.write("										");
 } 
      out.write("\r\n");
      out.write("										");
 if (asis != null && asis.getInstitucion() != null && !asis.getInstitucion().isBlank()) { 
      out.write("\r\n");
      out.write("                                                <div class=\"institucion\">\r\n");
      out.write("                                                    <u>Institución:</u> ");
      out.print( asis.getInstitucion() );
      out.write("\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            ");
 } 
      out.write("\r\n");
      out.write("                                            \r\n");
      out.write("                                        <!-- Información de seguidores y seguidos -->\r\n");
      out.write("                                        <div class=\"seguidores-info mt-3 pt-2\" style=\"border-top: 1px solid var(--border);\">\r\n");
      out.write("                                            <div class=\"seguidores mb-1\">\r\n");
      out.write("                                                <u>Seguidores:</u> <span class=\"fw-bold\">");
      out.print( request.getAttribute("cantidadSeguidores") != null ? request.getAttribute("cantidadSeguidores") : 0 );
      out.write("</span>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"seguidos\">\r\n");
      out.write("                                                <u>Siguiendo:</u> <span class=\"fw-bold\">");
      out.print( request.getAttribute("cantidadSeguidos") != null ? request.getAttribute("cantidadSeguidos") : 0 );
      out.write("</span>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("\r\n");
      out.write("							<div class=\"mt-4\">\r\n");
      out.write("								<div class=\"contenedor-ediciones\">\r\n");
      out.write("									");
 if (org != null) { 
      out.write("\r\n");
      out.write("										<div class=\"mb-2\">\r\n");
      out.write("											<a class=\"action-card\" href=\"");
      out.print(request.getContextPath());
      out.write("/listarEdiciones\" data-hotkey=\"2\" role=\"button\">\r\n");
      out.write("												<div class=\"action-icon d-flex align-items-center justify-content-center rounded\" style=\"width:44px;height:44px;border:1px solid var(--border);background:#fff\">\r\n");
      out.write("													<i class=\"bi bi-collection-fill\"></i>\r\n");
      out.write("												</div>\r\n");
      out.write("												<div class=\"flex-fill ms-2\">\r\n");
      out.write("													<h3 class=\"mb-0 h6 fw-bold\">Monitorear ediciones</h3>\r\n");
      out.write("													<p class=\"mb-0 small text-muted\">Permite ver estado de las ediciones y consultar detalles.</p>\r\n");
      out.write("												</div>\r\n");
      out.write("												<i class=\"bx bx-right-arrow-alt fs-4 text-secondary\"></i>\r\n");
      out.write("											</a>\r\n");
      out.write("										</div>\r\n");
      out.write("									");
 } else { 
      out.write("\r\n");
      out.write("										<div class=\"mt-4\">\r\n");
      out.write("											<div class=\"contenedor-ediciones\">\r\n");
      out.write("												<div class=\"mb-2\">\r\n");
      out.write("													<a class=\"action-card\" href=\"");
      out.print(request.getContextPath());
      out.write("/listarEdiciones\" data-hotkey=\"2\" role=\"button\">\r\n");
      out.write("														<div class=\"action-icon d-flex align-items-center justify-content-center rounded\" style=\"width:44px;height:44px;border:1px solid var(--border);background:#fff\">\r\n");
      out.write("															<i class=\"bi bi-collection-fill\"></i>\r\n");
      out.write("														</div>\r\n");
      out.write("														<div class=\"flex-fill ms-2\">\r\n");
      out.write("															<h3 class=\"mb-0 h6 fw-bold\">Mis Registros</h3>\r\n");
      out.write("															<p class=\"mb-0 small text-muted\">Ver y administrar mis registros en las ediciones.</p>\r\n");
      out.write("														</div>\r\n");
      out.write("														<i class=\"bx bx-right-arrow-alt fs-4 text-secondary\"></i>\r\n");
      out.write("													</a>\r\n");
      out.write("												</div>\r\n");
      out.write("											</div>\r\n");
      out.write("										</div>\r\n");
      out.write("									");
 } 
      out.write("\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</section>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"col-12 col-md-6 d-flex flex-column gap-3\">\r\n");
      out.write("					<section class=\"card mb-3 bg-light\">\r\n");
      out.write("						<div class=\"card-body p-0\">\r\n");
      out.write("							<ul class=\"list-unstyled m-0\">\r\n");
      out.write("								<li class=\"border-top\">\r\n");
      out.write("									<a href=\"");
      out.print(request.getContextPath());
      out.write("/modificarDatos?usuario=");
      out.print(encodedNick);
      out.write("\" class=\"d-grid gap-2 g-0 text-decoration-none p-3 align-items-center list-link\" id=\"mi-perfil-card\">\r\n");
      out.write("										<div class=\"d-flex align-items-center\">\r\n");
      out.write("											<div class=\"flex-fill\">\r\n");
      out.write("												<i class=\"bi bi-pencil-square\"></i><strong> Modificar mi usuario</strong>\r\n");
      out.write("												<div class=\"text-muted small\">Ver y editar datos personales, direccion, web y más.</div>\r\n");
      out.write("											</div>\r\n");
      out.write("											<div class=\"ms-2 text-secondary\" aria-hidden=\"true\">\r\n");
      out.write("												<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"18\" height=\"18\" fill=\"currentColor\" viewBox=\"0 0 16 16\"><path d=\"M6 12.796V3.204L11.481 8 6 12.796zm.659.753 5.48-4.796a1 1 0 0 0 0-1.506L6.66 2.451C6.011 1.885 5 2.345 5 3.204v9.592a1 1 0 0 0 1.659.753z\"/></svg>\r\n");
      out.write("											</div>\r\n");
      out.write("									</div>\r\n");
      out.write("									</a>\r\n");
      out.write("								</li>\r\n");
      out.write("							</ul>\r\n");
      out.write("						</div>\r\n");
      out.write("					</section>\r\n");
      out.write("\r\n");
      out.write("					");
 if (org != null) { 
      out.write("\r\n");
      out.write("					<section class=\"card mb-3 bg-light\">\r\n");
      out.write("						<div class=\"card-body\">\r\n");
      out.write("							<div class=\"mb-3\"><h2 class=\"h6 mb-0 fw-bold\">Acciones</h2></div>\r\n");
      out.write("							<div class=\"col actions-grid\" role=\"navigation\" aria-label=\"Acciones de perfil\">\r\n");
      out.write("								<div class=\"row-4 mb-2\">\r\n");
      out.write("									<a class=\"action-card\" href=\"");
      out.print(request.getContextPath());
      out.write("/altaEvento\" data-hotkey=\"3\" role=\"button\">\r\n");
      out.write("										<div class=\"action-icon d-flex align-items-center justify-content-center rounded\" style=\"width:44px;height:44px;border:1px solid var(--border);background:#fff\"><i class='bx bx-calendar-plus fs-4' aria-hidden=\"true\"></i></div>\r\n");
      out.write("										<div class=\"flex-fill ms-2\"><h3 class=\"mb-0 h6 fw-bold\">Alta evento</h3><p class=\"mb-0 small text-muted\">Crea un nuevo evento con sus datos básicos.</p></div>\r\n");
      out.write("										<i class=\"bx bx-right-arrow-alt fs-4 text-secondary\"></i>\r\n");
      out.write("									</a>\r\n");
      out.write("								</div>\r\n");
      out.write("								<!-- New action: Alta institución for organizers -->\r\n");
      out.write("								<div class=\"row-4 mb-2\">\r\n");
      out.write("									<a class=\"action-card\" href=\"");
      out.print(request.getContextPath());
      out.write("/altaInstitucion\" data-hotkey=\"4\" role=\"button\">\r\n");
      out.write("										<div class=\"action-icon d-flex align-items-center justify-content-center rounded\" style=\"width:44px;height:44px;border:1px solid var(--border);background:#fff\"><i class='bx bx-building fs-4' aria-hidden=\"true\"></i></div>\r\n");
      out.write("										<div class=\"flex-fill ms-2\"><h3 class=\"mb-0 h6 fw-bold\">Alta institución</h3><p class=\"mb-0 small text-muted\">Registrar una nueva institución colaboradora.</p></div>\r\n");
      out.write("										<i class=\"bx bx-right-arrow-alt fs-4 text-secondary\"></i>\r\n");
      out.write("									</a>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</section>\r\n");
      out.write("					");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</main>\r\n");
      out.write("\r\n");
      out.write("	<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("	<script>\r\n");
      out.write("	(function () {\r\n");
      out.write("	  var toggle = document.getElementById('header-toggle');\r\n");
      out.write("	  var sidebar = document.getElementById('nav-bar-perfil');\r\n");
      out.write("	  var body = document.getElementById('body-pd');\r\n");
      out.write("\r\n");
      out.write("	  if (toggle && sidebar) {\r\n");
      out.write("	    toggle.addEventListener('click', function(){\r\n");
      out.write("	      var isCollapsed = sidebar.classList.toggle('collapsed');\r\n");
      out.write("	      document.body.classList.toggle('with-collapsed');\r\n");
      out.write("	      toggle.setAttribute('aria-expanded', String(!isCollapsed));\r\n");
      out.write("	    });\r\n");
      out.write("	  }\r\n");
      out.write("\r\n");
      out.write("	  document.addEventListener('keydown', function(e){\r\n");
      out.write("	    if (e && e.key >= '1' && e.key <= '6' && !e.altKey && !e.ctrlKey && !e.metaKey) {\r\n");
      out.write("	      var selector = '[data-hotkey=\"' + e.key + '\"]';\r\n");
      out.write("	      var el = document.querySelector(selector);\r\n");
      out.write("	      if (el) el.click();\r\n");
      out.write("	    }\r\n");
      out.write("	  });\r\n");
      out.write("	}());\r\n");
      out.write("	</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
