/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.13
 * Generated at: 2025-12-06 06:15:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.pages;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class registro_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"es\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <meta http-equiv=\"Cache-Control\" content=\"no-cache, no-store, must-revalidate\" />\r\n");
      out.write("    <meta http-equiv=\"Pragma\" content=\"no-cache\" />\r\n");
      out.write("    <meta http-equiv=\"Expires\" content=\"0\" />\r\n");
      out.write("    <title>Registrarse - Eventos.uy</title>\r\n");
      out.write("    \r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/assets/css/index.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css2?family=Inter&display=swap\" />\r\n");
      out.write("    <link rel=\"icon\" type=\"image/x-icon\" href=\"");
      out.print(request.getContextPath());
      out.write("/assets/icons/Logo.png\">\r\n");
      out.write("    \r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/assets/css/ConsultaEvento.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/assets/css/styles.css\">\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/boxicons@latest/css/boxicons.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Titillium+Web:wght@300;400;600&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    \r\n");
      out.write("    <!-- Estilos simples para mensajes de disponibilidad -->\r\n");
      out.write("    <style>\r\n");
      out.write("        .availability-available {\r\n");
      out.write("            color: #198754 !important;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .availability-unavailable {\r\n");
      out.write("            color: #dc3545 !important;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../templates/header.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"container d-flex justify-content-center\">\r\n");
      out.write("        \r\n");
      out.write("        <!-- Contenedor del formulario -->\r\n");
      out.write("        <div class=\"col-md-5 col-lg-7 col-xxl-9 mt-3 mt-sm-3 mt-md-0 Registro base text-center\">\r\n");
      out.write("            <h1 class=\"mb-5\">\r\n");
      out.write("                <strong></strong>\r\n");
      out.write("            </h1>\r\n");
      out.write("            <h3 class=\"mb-4\">\r\n");
      out.write("                <strong>Registrarse</strong>\r\n");
      out.write("            </h3>\r\n");
      out.write("\r\n");
      out.write("            <!-- Mostrar errores si existen -->\r\n");
      out.write("            ");
 if (request.getAttribute("error") != null) { 
      out.write("\r\n");
      out.write("                <div class=\"alert alert-danger\" role=\"alert\">\r\n");
      out.write("                    ");
      out.print( request.getAttribute("error") );
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("            <p class=\"mb-3\">Introduce tus datos de usuario para crear una cuenta nueva</p>\r\n");
      out.write("            \r\n");
      out.write("            <form id=\"registroForm\" action=\"");
      out.print(request.getContextPath());
      out.write("/registro\" method=\"post\" class=\"needs-validation\" autocomplete=\"off\" enctype=\"multipart/form-data\">\r\n");
      out.write("                \r\n");
      out.write("                <!-- Campos básicos -->\r\n");
      out.write("                <div class=\"mb-3\">\r\n");
      out.write("                    <input type=\"text\" class=\"form-control\" id=\"nickname\" name=\"nickname\" \r\n");
      out.write("                           placeholder=\"Apodo *\" \r\n");
      out.write("                           value=\"");
      out.print( request.getAttribute("nickname") != null ? request.getAttribute("nickname") : "" );
      out.write("\" \r\n");
      out.write("                           required autocomplete=\"off\"\r\n");
      out.write("                           oninvalid=\"this.setCustomValidity('Por favor ingrese un apodo.')\"\r\n");
      out.write("                           oninput=\"this.setCustomValidity(''); verificarNickname()\">\r\n");
      out.write("                    <div class=\"invalid-feedback\">\r\n");
      out.write("                        Por favor ingrese un apodo.\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <small id=\"nicknameStatus\" class=\"text-muted\"></small>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"mb-3\">\r\n");
      out.write("                    <input type=\"text\" class=\"form-control\" id=\"nombre\" name=\"nombre\" \r\n");
      out.write("                           placeholder=\"Nombre *\" \r\n");
      out.write("                           value=\"");
      out.print( request.getAttribute("nombre") != null ? request.getAttribute("nombre") : "" );
      out.write("\" \r\n");
      out.write("                           required autocomplete=\"off\"\r\n");
      out.write("                           oninvalid=\"this.setCustomValidity('Por favor ingrese su nombre.')\"\r\n");
      out.write("                           oninput=\"this.setCustomValidity('')\">\r\n");
      out.write("                    <div class=\"invalid-feedback\">\r\n");
      out.write("                        Por favor ingrese su nombre.\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"mb-3\">\r\n");
      out.write("                    <input type=\"email\" class=\"form-control\" id=\"email\" name=\"email\" \r\n");
      out.write("                           placeholder=\"Correo electrónico *\" \r\n");
      out.write("                           value=\"");
      out.print( request.getAttribute("email") != null ? request.getAttribute("email") : "" );
      out.write("\" \r\n");
      out.write("                           required autocomplete=\"off\"\r\n");
      out.write("                           oninvalid=\"if(this.validity.valueMissing) this.setCustomValidity('Por favor ingrese un correo electrónico.'); else if(this.validity.typeMismatch) this.setCustomValidity('Por favor ingrese un correo electrónico válido.');\"\r\n");
      out.write("                           oninput=\"this.setCustomValidity(''); verificarEmail()\">\r\n");
      out.write("                    <div class=\"invalid-feedback\">\r\n");
      out.write("                        Por favor ingrese un correo electrónico válido.\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <small id=\"emailStatus\" class=\"text-muted\"></small>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"mb-3\">\r\n");
      out.write("                    <input type=\"password\" class=\"form-control\" id=\"password\" name=\"password\" \r\n");
      out.write("                           placeholder=\"Contraseña *\" required autocomplete=\"off\" minlength=\"6\"\r\n");
      out.write("                           oninvalid=\"if(this.validity.valueMissing) this.setCustomValidity('Por favor ingrese una contraseña.'); else if(this.validity.tooShort) this.setCustomValidity('La contraseña debe tener al menos 6 caracteres.');\"\r\n");
      out.write("                           oninput=\"this.setCustomValidity(''); validatePasswordMatch();\">\r\n");
      out.write("                    <div class=\"invalid-feedback\">\r\n");
      out.write("                        La contraseña debe tener al menos 6 caracteres.\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"mb-3\">\r\n");
      out.write("                    <input type=\"password\" class=\"form-control\" id=\"confirmPassword\" name=\"confirmPassword\" \r\n");
      out.write("                           placeholder=\"Confirmar contraseña *\" required autocomplete=\"off\" minlength=\"6\"\r\n");
      out.write("                           oninvalid=\"if(this.validity.valueMissing) this.setCustomValidity('Por favor ingrese una contraseña.'); else if(this.validity.tooShort) this.setCustomValidity('La contraseña debe tener al menos 6 caracteres.');\r\n");
      out.write("                           else if(this.value != document.getElementById('password').value) this.setCustomValidity('La contraseña no coincide.');\"\r\n");
      out.write("                           oninput=\"validatePasswordMatch()\">\r\n");
      out.write("                    <div class=\"invalid-feedback\">\r\n");
      out.write("                        La contraseña no coincide.\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"mb-3\">\r\n");
      out.write("                    <input type=\"file\" class=\"form-control\" id=\"imgPerfil\" name=\"imagen\"\r\n");
      out.write("                           accept=\"image/*\">\r\n");
      out.write("                    <small class=\"text-muted\">Formatos admitidos: JPG, PNG, GIF. Tamaño máximo: 5MB</small>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <!-- Tipo de usuario -->\r\n");
      out.write("                <div class=\"mb-3\">\r\n");
      out.write("                    <label class=\"form-label\">Tipo de usuario: <span class=\"text-danger\">*</span></label>\r\n");
      out.write("                    <div class=\"d-flex justify-content-center align-items-center gap-4\">\r\n");
      out.write("                        <div class=\"form-check\">\r\n");
      out.write("                            <input type=\"radio\" class=\"form-check-input\" id=\"tipoAsistente\" name=\"tipoUsuario\" value=\"asistente\"\r\n");
      out.write("                                   ");
      out.print( !"organizador".equals(request.getAttribute("tipoUsuario")) ? "checked" : "" );
      out.write("\r\n");
      out.write("                                   required\r\n");
      out.write("                                   oninvalid=\"this.setCustomValidity('Por favor seleccione un tipo de usuario.')\"\r\n");
      out.write("                                   onchange=\"this.setCustomValidity(''); toggleUserFields()\">\r\n");
      out.write("                            <label class=\"form-check-label\" for=\"tipoAsistente\">\r\n");
      out.write("                                Asistente\r\n");
      out.write("                            </label>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"form-check\">\r\n");
      out.write("                            <input type=\"radio\" class=\"form-check-input\" id=\"tipoOrganizador\" name=\"tipoUsuario\" value=\"organizador\"\r\n");
      out.write("                                   ");
      out.print( "organizador".equals(request.getAttribute("tipoUsuario")) ? "checked" : "" );
      out.write("\r\n");
      out.write("                                   required\r\n");
      out.write("                                   oninvalid=\"this.setCustomValidity('Por favor seleccione un tipo de usuario.')\"\r\n");
      out.write("                                   onchange=\"this.setCustomValidity(''); toggleUserFields()\">\r\n");
      out.write("                            <label class=\"form-check-label\" for=\"tipoOrganizador\">\r\n");
      out.write("                                Organizador\r\n");
      out.write("                            </label>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"invalid-feedback\" id=\"tipoInvalidFeedback\">\r\n");
      out.write("                        Por favor seleccione un tipo de usuario.\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- Campos específicos para Asistente -->\r\n");
      out.write("                <div id=\"asistenteFields\" style=\"");
      out.print( "organizador".equals(request.getAttribute("tipoUsuario")) ? "display: none;" : "" );
      out.write("\">\r\n");
      out.write("                    <div class=\"mb-3\">\r\n");
      out.write("                        <input type=\"text\" class=\"form-control\" id=\"apellido\" name=\"apellido\" \r\n");
      out.write("                               placeholder=\"Apellido *\" \r\n");
      out.write("                               value=\"");
      out.print( request.getAttribute("apellido") != null ? request.getAttribute("apellido") : "" );
      out.write("\" \r\n");
      out.write("                               required autocomplete=\"off\"\r\n");
      out.write("                               oninvalid=\"this.setCustomValidity('Por favor ingrese su apellido.')\"\r\n");
      out.write("                               oninput=\"this.setCustomValidity('')\">\r\n");
      out.write("                        <div class=\"invalid-feedback\">\r\n");
      out.write("                            Por favor ingrese su apellido.\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                    <div class=\"mb-3\">\r\n");
      out.write("                        <input type=\"date\" class=\"form-control\" id=\"fechaNacimiento\" name=\"fechaNacimiento\" \r\n");
      out.write("                               value=\"");
      out.print( request.getAttribute("fechaNacimiento") != null ? request.getAttribute("fechaNacimiento") : "" );
      out.write("\"\r\n");
      out.write("                               required\r\n");
      out.write("                               oninvalid=\"this.setCustomValidity('Por favor ingrese su fecha de nacimiento.')\"\r\n");
      out.write("                               oninput=\"validateFechaNacimiento(this)\">\r\n");
      out.write("                        <small class=\"text-muted\">Fecha de nacimiento *</small>\r\n");
      out.write("                        <div class=\"invalid-feedback\" id=\"fechaNacimientoError\">\r\n");
      out.write("                            Por favor ingrese una fecha de nacimiento válida.\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                    <!-- Selector de institución -->\r\n");
      out.write("                    <div class=\"mb-3\">\r\n");
      out.write("                        <label for=\"institucionSelect\" class=\"form-label\">Si perteneces a una institución, seleccionala.</label>\r\n");
      out.write("                        <select class=\"form-select\" id=\"institucionSelect\" name=\"institucion\" aria-label=\"Selecciona una institución\">\r\n");
      out.write("                            <option value=\"\">Selecciona una institución (opcional)</option>\r\n");
      out.write("                            ");

                                java.util.Set<String> instituciones = (java.util.Set<String>) request.getAttribute("instituciones");
                                String institucionSeleccionada = (String) request.getAttribute("institucion");
                                if (instituciones != null && !instituciones.isEmpty()) {
                                    for (String institucion : instituciones) {
                                        String selected = java.util.Objects.equals(institucion, institucionSeleccionada) ? " selected" : "";
                            
      out.write("\r\n");
      out.write("                                <option value=\"");
      out.print( institucion );
      out.write('"');
      out.print( selected );
      out.write('>');
      out.print( institucion );
      out.write("</option>\r\n");
      out.write("                            ");

                                    }
                                }
                            
      out.write("\r\n");
      out.write("                        </select>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- Campos específicos para Organizador -->\r\n");
      out.write("                <div id=\"organizadorFields\" style=\"");
      out.print( !"organizador".equals(request.getAttribute("tipoUsuario")) ? "display: none;" : "" );
      out.write("\">\r\n");
      out.write("                    <div class=\"mb-3\">\r\n");
      out.write("                        <label for=\"descripcion\" class=\"form-label\">Una breve descripción de su organización *</label>\r\n");
      out.write("                        <textarea class=\"form-control\" name=\"descripcion\" id=\"descripcion\" rows=\"3\"\r\n");
      out.write("                                  autocomplete=\"off\" required oninvalid=\"this.setCustomValidity('Por favor ingrese una descripción.')\"\r\n");
      out.write("                                  oninput=\"this.setCustomValidity('')\">");
      out.print( request.getAttribute("descripcion") != null ? request.getAttribute("descripcion") : "" );
      out.write("</textarea>\r\n");
      out.write("                        <div class=\"invalid-feedback\">\r\n");
      out.write("                            Por favor ingrese una descripción.\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                    <div class=\"mb-3\">\r\n");
      out.write("                        <input type=\"url\" class=\"form-control\" id=\"sitioWeb\" name=\"sitioWeb\" \r\n");
      out.write("                               placeholder=\"URL a su sitio web (opcional)\" \r\n");
      out.write("                               value=\"");
      out.print( request.getAttribute("sitioWeb") != null ? request.getAttribute("sitioWeb") : "" );
      out.write("\" \r\n");
      out.write("                               autocomplete=\"off\">\r\n");
      out.write("                        <small class=\"text-muted\">Campo opcional</small>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <button type=\"submit\" class=\"btn btn-dark\">\r\n");
      out.write("                    <span id=\"botonTexto\">Continuar</span>\r\n");
      out.write("                </button>\r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Solo Bootstrap -->\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("    <script>\r\n");
      out.write("    \r\n");
      out.write("        function toggleUserFields() {\r\n");
      out.write("            const tipoAsistente = document.getElementById('tipoAsistente').checked;\r\n");
      out.write("            const asistenteFields = document.getElementById('asistenteFields');\r\n");
      out.write("            const organizadorFields = document.getElementById('organizadorFields');\r\n");
      out.write("            \r\n");
      out.write("            const apellidoField = document.getElementById('apellido');\r\n");
      out.write("            const fechaNacimientoField = document.getElementById('fechaNacimiento');\r\n");
      out.write("            \r\n");
      out.write("            const descripcionField = document.getElementById('descripcion');\r\n");
      out.write("            const sitioWebField = document.getElementById('sitioWeb');\r\n");
      out.write("            \r\n");
      out.write("            if (tipoAsistente) {\r\n");
      out.write("                asistenteFields.style.display = 'block';\r\n");
      out.write("                organizadorFields.style.display = 'none';\r\n");
      out.write("                \r\n");
      out.write("                apellidoField.required = true;\r\n");
      out.write("                fechaNacimientoField.required = true;\r\n");
      out.write("                \r\n");
      out.write("                descripcionField.required = false;\r\n");
      out.write("                sitioWebField.required = false;\r\n");
      out.write("            } else {\r\n");
      out.write("                asistenteFields.style.display = 'none';\r\n");
      out.write("                organizadorFields.style.display = 'block';\r\n");
      out.write("                \r\n");
      out.write("                apellidoField.required = false;\r\n");
      out.write("                fechaNacimientoField.required = false;\r\n");
      out.write("                \r\n");
      out.write("                descripcionField.required = true;\r\n");
      out.write("                sitioWebField.required = false; \r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        function validateFechaNacimiento(input) {\r\n");
      out.write("            const fechaNacimiento = new Date(input.value);\r\n");
      out.write("            const hoy = new Date();\r\n");
      out.write("            \r\n");
      out.write("            input.setCustomValidity('');\r\n");
      out.write("            document.getElementById('fechaNacimientoError').style.display = 'none';\r\n");
      out.write("            \r\n");
      out.write("            if (fechaNacimiento > hoy) {\r\n");
      out.write("                input.setCustomValidity('La fecha de nacimiento no puede ser en el futuro.');\r\n");
      out.write("                document.getElementById('fechaNacimientoError').style.display = 'block';\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        document.addEventListener('DOMContentLoaded', function() {\r\n");
      out.write("            toggleUserFields();\r\n");
      out.write("        });\r\n");
      out.write("        \r\n");
      out.write("        window.addEventListener(\"pageshow\", function(event) {\r\n");
      out.write("            if (event.persisted) {\r\n");
      out.write("                window.location.reload();\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("        \r\n");
      out.write("        function validatePasswordMatch() {\r\n");
      out.write("            const password = document.getElementById('password');\r\n");
      out.write("            const confirmPassword = document.getElementById('confirmPassword');\r\n");
      out.write("            \r\n");
      out.write("            confirmPassword.setCustomValidity('');\r\n");
      out.write("            \r\n");
      out.write("            if (confirmPassword.value === '') {\r\n");
      out.write("                return; \r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            //CHECKEAMOS QUE LAS CONTRASENIAS COINCIDAN\r\n");
      out.write("            if (password.value !== confirmPassword.value) {\r\n");
      out.write("                confirmPassword.setCustomValidity('Las contraseñas no coinciden.');\r\n");
      out.write("                \r\n");
      out.write("                confirmPassword.classList.add('is-invalid');\r\n");
      out.write("                confirmPassword.classList.remove('is-valid');\r\n");
      out.write("            } else {\r\n");
      out.write("                confirmPassword.setCustomValidity('');\r\n");
      out.write("                confirmPassword.classList.add('is-valid');\r\n");
      out.write("                confirmPassword.classList.remove('is-invalid');\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("		\r\n");
      out.write("        //actualizamos para ver si coincide o no\r\n");
      out.write("        document.addEventListener('DOMContentLoaded', function() {\r\n");
      out.write("            const password = document.getElementById('password');\r\n");
      out.write("            const confirmPassword = document.getElementById('confirmPassword');\r\n");
      out.write("            \r\n");
      out.write("            password.addEventListener('input', validatePasswordMatch);\r\n");
      out.write("            confirmPassword.addEventListener('input', validatePasswordMatch);\r\n");
      out.write("            \r\n");
      out.write("            document.getElementById('registroForm').addEventListener('submit', function(event) {\r\n");
      out.write("                if (password.value !== confirmPassword.value && confirmPassword.value !== '') {\r\n");
      out.write("                    event.preventDefault();\r\n");
      out.write("                    confirmPassword.setCustomValidity('Las contraseñas no coinciden.');\r\n");
      out.write("                    confirmPassword.classList.add('is-invalid');\r\n");
      out.write("                    confirmPassword.reportValidity();\r\n");
      out.write("                }\r\n");
      out.write("            });\r\n");
      out.write("            \r\n");
      out.write("            toggleUserFields();\r\n");
      out.write("        });\r\n");
      out.write("        \r\n");
      out.write("        function verificarNickname() {\r\n");
      out.write("            const nickname = document.getElementById('nickname').value;\r\n");
      out.write("            const status = document.getElementById('nicknameStatus');\r\n");
      out.write("            \r\n");
      out.write("        \r\n");
      out.write("            \r\n");
      out.write("            // Llamada AJAX real\r\n");
      out.write("            const xhr = new XMLHttpRequest();\r\n");
      out.write("            xhr.open('GET', '");
      out.print(request.getContextPath());
      out.write("/verificar-disponibilidad?tipo=nickname&valor=' + encodeURIComponent(nickname), true);\r\n");
      out.write("            xhr.onreadystatechange = function() {\r\n");
      out.write("                if (xhr.readyState === 4 && xhr.status === 200) {\r\n");
      out.write("                    try {\r\n");
      out.write("                        const response = JSON.parse(xhr.responseText);\r\n");
      out.write("                        if (response.disponible) {\r\n");
      out.write("                            status.textContent = 'Apodo disponible.';\r\n");
      out.write("                            status.className = 'availability-available';\r\n");
      out.write("                        } else {\r\n");
      out.write("                            status.textContent = 'Apodo no disponible.';\r\n");
      out.write("                            status.className = 'availability-unavailable';\r\n");
      out.write("                        }\r\n");
      out.write("                    } catch (e) {\r\n");
      out.write("                        status.textContent = 'Error al verificar disponibilidad.';\r\n");
      out.write("                        status.className = 'availability-unavailable';\r\n");
      out.write("                    }\r\n");
      out.write("                }\r\n");
      out.write("            };\r\n");
      out.write("            xhr.send();\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        function verificarEmail() {\r\n");
      out.write("            const email = document.getElementById('email').value;\r\n");
      out.write("            const status = document.getElementById('emailStatus');\r\n");
      out.write("            \r\n");
      out.write("            if (!validateEmail(email)) {\r\n");
      out.write("                status.textContent = 'Ingrese un correo electrónico válido.';\r\n");
      out.write("                status.className = 'text-danger availability-unavailable';\r\n");
      out.write("                return;\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            // Llamada AJAX real\r\n");
      out.write("            const xhr = new XMLHttpRequest();\r\n");
      out.write("            xhr.open('GET', '");
      out.print(request.getContextPath());
      out.write("/verificar-disponibilidad?tipo=email&valor=' + encodeURIComponent(email), true);\r\n");
      out.write("            xhr.onreadystatechange = function() {\r\n");
      out.write("                if (xhr.readyState === 4 && xhr.status === 200) {\r\n");
      out.write("                    try {\r\n");
      out.write("                        const response = JSON.parse(xhr.responseText);\r\n");
      out.write("                        if (response.disponible) {\r\n");
      out.write("                            status.textContent = 'Correo electrónico disponible.';\r\n");
      out.write("                            status.className = 'availability-available';\r\n");
      out.write("                        } else {\r\n");
      out.write("                            status.textContent = 'Correo electrónico no disponible.';\r\n");
      out.write("                            status.className = 'availability-unavailable';\r\n");
      out.write("                        }\r\n");
      out.write("                    } catch (e) {\r\n");
      out.write("                        status.textContent = 'Error al verificar disponibilidad.';\r\n");
      out.write("                        status.className = 'availability-unavailable';\r\n");
      out.write("                    }\r\n");
      out.write("                }\r\n");
      out.write("            };\r\n");
      out.write("            xhr.send();\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        function validateEmail(email) {\r\n");
      out.write("            const re = /^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$/;\r\n");
      out.write("            return re.test(String(email).toLowerCase());\r\n");
      out.write("        }\r\n");
      out.write("		\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
