/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.13
 * Generated at: 2025-12-05 17:13:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.templates;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import webservices.*;

public final class header_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("webservices");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://fonts.googleapis.com/css2?family=Inter&display=swap\" />\r\n");
      out.write("<link rel=\"icon\" type=\"image/x-icon\" href=\"../assets/icons/Logo.png\">\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css\"\r\n");
      out.write("	rel=\"stylesheet\"\r\n");
      out.write("	integrity=\"sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB\"\r\n");
      out.write("	crossorigin=\"anonymous\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.css\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://fonts.googleapis.com/css2?family=Inter&display=swap\" />\r\n");
      out.write("<link rel=\"icon\" type=\"image/x-icon\" href=\"assets/icons/Logo.png\">\r\n");
      out.write("<!-- Icono de la pestaña -->\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css\"\r\n");
      out.write("	rel=\"stylesheet\"\r\n");
      out.write("	integrity=\"sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB\"\r\n");
      out.write("	crossorigin=\"anonymous\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.css\">\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"assets/css/styles.css\">\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
 
	DataUsuario user = (DataUsuario) session.getAttribute("usuario");
	// Obtener valores para la searchbar
    String valorBusqueda = request.getParameter("nombre");
    if (valorBusqueda == null) {
        valorBusqueda = (String) request.getAttribute("nombreBusqueda");
    }
    if (valorBusqueda == null) {
        valorBusqueda = "";
    }
    
    String tipoFiltro = request.getParameter("tipo");
    if (tipoFiltro == null) {
        tipoFiltro = (String) request.getAttribute("tipoFiltro");
    }
    
    String ordenamiento = request.getParameter("orden");
    if (ordenamiento == null) {
        ordenamiento = (String) request.getAttribute("ordenamiento");
    }
	
	if (user == null) { 
      out.write("\r\n");
      out.write("	<header>\r\n");
      out.write("		<nav class=\"navbar bg-white shadow-sm\" style=\"height: 86px;\">\r\n");
      out.write("			<div>\r\n");
      out.write("				<a class=\"fw-bold text-dark fs-2 m-4 text-decoration-none\" href=\"HomeServlet\"><b>Eventos.uy</b></a>\r\n");
      out.write("			</div>\r\n");
      out.write("			\r\n");
      out.write("			<!-- Searchbar simplificada en el centro -->\r\n");
      out.write("			<div class=\"text-center\" style=\"flex: 1;\">\r\n");
      out.write("				<form action=\"");
      out.print(request.getContextPath());
      out.write("/eventos\" method=\"get\" class=\"d-flex justify-content-center align-items-center gap-2\" style=\"max-width: 500px; margin: 0 auto;\">\r\n");
      out.write("					<input type=\"search\" name=\"nombre\" class=\"search flex-grow-1\"\r\n");
      out.write("					       placeholder=\"Buscar eventos o ediciones...\" \r\n");
      out.write("					       value=\"");
      out.print(valorBusqueda);
      out.write("\">\r\n");
      out.write("					<div class=\"dropdown\">\r\n");
      out.write("						<button class=\"btn btn-outline-secondary btn-sm dropdown-toggle\" type=\"button\" \r\n");
      out.write("						        id=\"filtrosDropdown\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("							<i class=\"bi bi-funnel\"></i>\r\n");
      out.write("						</button>\r\n");
      out.write("						<div class=\"dropdown-menu p-3\" style=\"min-width: 220px;\">\r\n");
      out.write("							<div class=\"mb-3\">\r\n");
      out.write("								<strong>Tipo:</strong>\r\n");
      out.write("								<div class=\"form-check\">\r\n");
      out.write("									<input class=\"form-check-input\" type=\"radio\" name=\"tipo\" value=\"\" id=\"tipoAmbos\"\r\n");
      out.write("									       ");
      out.print((tipoFiltro == null || tipoFiltro.isEmpty()) ? "checked" : "");
      out.write(">\r\n");
      out.write("									<label class=\"form-check-label\" for=\"tipoAmbos\">Ambos</label>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"form-check\">\r\n");
      out.write("									<input class=\"form-check-input\" type=\"radio\" name=\"tipo\" value=\"eventos\" id=\"tipoEventos\"\r\n");
      out.write("									       ");
      out.print("eventos".equals(tipoFiltro) ? "checked" : "");
      out.write(">\r\n");
      out.write("									<label class=\"form-check-label\" for=\"tipoEventos\">Solo eventos</label>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"form-check\">\r\n");
      out.write("									<input class=\"form-check-input\" type=\"radio\" name=\"tipo\" value=\"ediciones\" id=\"tipoEdiciones\"\r\n");
      out.write("									       ");
      out.print("ediciones".equals(tipoFiltro) ? "checked" : "");
      out.write(">\r\n");
      out.write("									<label class=\"form-check-label\" for=\"tipoEdiciones\">Solo ediciones</label>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"mb-3\">\r\n");
      out.write("								<strong>Ordenar:</strong>\r\n");
      out.write("								<div class=\"form-check\">\r\n");
      out.write("									<input class=\"form-check-input\" type=\"radio\" name=\"orden\" value=\"\" id=\"ordenFecha\"\r\n");
      out.write("									       ");
      out.print((ordenamiento == null || ordenamiento.isEmpty()) ? "checked" : "");
      out.write(">\r\n");
      out.write("									<label class=\"form-check-label\" for=\"ordenFecha\">Por fecha</label>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"form-check\">\r\n");
      out.write("									<input class=\"form-check-input\" type=\"radio\" name=\"orden\" value=\"alfabetico\" id=\"ordenAlfabetico\"\r\n");
      out.write("									       ");
      out.print("alfabetico".equals(ordenamiento) ? "checked" : "");
      out.write(">\r\n");
      out.write("									<label class=\"form-check-label\" for=\"ordenAlfabetico\">Alfabético</label>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<button type=\"submit\" class=\"btn btn-primary btn-sm w-100\">Buscar</button>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</form>\r\n");
      out.write("			</div>\r\n");
      out.write("			\r\n");
      out.write("			<div class=\"header-auth m-3 d-flex justify-content-end\">\r\n");
      out.write("				<a href=\"iniciosesion\" class=\"text-decoration-none\">\r\n");
      out.write("					<button type=\"button\" class=\"button1 rounded-3\">\r\n");
      out.write("						<div class=\"header-button\">Iniciar sesión</div>\r\n");
      out.write("					</button>\r\n");
      out.write("				</a> <a href=\"registro\" class=\"text-decoration-none\">\r\n");
      out.write("					<button type=\"button\" class=\"button2 rounded-3\">\r\n");
      out.write("						<div class=\"header-button\">Regístrarse</div>\r\n");
      out.write("					</button>\r\n");
      out.write("				</a>\r\n");
      out.write("			</div>\r\n");
      out.write("		</nav>\r\n");
      out.write("	</header>\r\n");
      out.write("	");
 } else { 
      out.write(" \r\n");
      out.write("	\r\n");
      out.write("	<header>\r\n");
      out.write("		<nav class=\"navbar bg-white shadow-sm\">\r\n");
      out.write("			<div>\r\n");
      out.write("				<a class=\"fw-bold text-dark fs-2 m-4 text-decoration-none\" href=\"HomeServlet\"><b>Eventos.uy</b></a>\r\n");
      out.write("			</div>\r\n");
      out.write("			\r\n");
      out.write("			<!-- Searchbar simplificada en el centro -->\r\n");
      out.write("			<div class=\"text-center\" style=\"flex: 1;\">\r\n");
      out.write("				<form action=\"");
      out.print(request.getContextPath());
      out.write("/eventos\" method=\"get\" class=\"d-flex justify-content-center align-items-center gap-2\" style=\"max-width: 500px; margin: 0 auto;\">\r\n");
      out.write("					<input type=\"search\" name=\"nombre\" class=\"search flex-grow-1\"\r\n");
      out.write("					       placeholder=\"Buscar eventos o ediciones...\" \r\n");
      out.write("					       value=\"");
      out.print(valorBusqueda);
      out.write("\">\r\n");
      out.write("					<div class=\"dropdown\">\r\n");
      out.write("						<button class=\"btn btn-outline-secondary btn-sm dropdown-toggle\" type=\"button\" \r\n");
      out.write("						        id=\"filtrosDropdown\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("							<i class=\"bi bi-funnel\"></i>\r\n");
      out.write("						</button>\r\n");
      out.write("						<div class=\"dropdown-menu p-3\" style=\"min-width: 220px;\">\r\n");
      out.write("							<div class=\"mb-3\">\r\n");
      out.write("								<strong>Tipo:</strong>\r\n");
      out.write("								<div class=\"form-check\">\r\n");
      out.write("									<input class=\"form-check-input\" type=\"radio\" name=\"tipo\" value=\"\" id=\"tipoAmbos\"\r\n");
      out.write("									       ");
      out.print((tipoFiltro == null || tipoFiltro.isEmpty()) ? "checked" : "");
      out.write(">\r\n");
      out.write("									<label class=\"form-check-label\" for=\"tipoAmbos\">Ambos</label>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"form-check\">\r\n");
      out.write("									<input class=\"form-check-input\" type=\"radio\" name=\"tipo\" value=\"eventos\" id=\"tipoEventos\"\r\n");
      out.write("									       ");
      out.print("eventos".equals(tipoFiltro) ? "checked" : "");
      out.write(">\r\n");
      out.write("									<label class=\"form-check-label\" for=\"tipoEventos\">Solo eventos</label>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"form-check\">\r\n");
      out.write("									<input class=\"form-check-input\" type=\"radio\" name=\"tipo\" value=\"ediciones\" id=\"tipoEdiciones\"\r\n");
      out.write("									       ");
      out.print("ediciones".equals(tipoFiltro) ? "checked" : "");
      out.write(">\r\n");
      out.write("									<label class=\"form-check-label\" for=\"tipoEdiciones\">Solo ediciones</label>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"mb-3\">\r\n");
      out.write("								<strong>Ordenar:</strong>\r\n");
      out.write("								<div class=\"form-check\">\r\n");
      out.write("									<input class=\"form-check-input\" type=\"radio\" name=\"orden\" value=\"\" id=\"ordenFecha\"\r\n");
      out.write("									       ");
      out.print((ordenamiento == null || ordenamiento.isEmpty()) ? "checked" : "");
      out.write(">\r\n");
      out.write("									<label class=\"form-check-label\" for=\"ordenFecha\">Por fecha</label>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"form-check\">\r\n");
      out.write("									<input class=\"form-check-input\" type=\"radio\" name=\"orden\" value=\"alfabetico\" id=\"ordenAlfabetico\"\r\n");
      out.write("									       ");
      out.print("alfabetico".equals(ordenamiento) ? "checked" : "");
      out.write(">\r\n");
      out.write("									<label class=\"form-check-label\" for=\"ordenAlfabetico\">Alfabético</label>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<button type=\"submit\" class=\"btn btn-primary btn-sm w-100\">Buscar</button>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</form>\r\n");
      out.write("			</div>\r\n");
      out.write("			\r\n");
      out.write("			<div class=\"d-flex justify-content-end align-items-center\">\r\n");
      out.write("				<div class=\"dropdown\">\r\n");
      out.write("					<a class=\"d-flex align-items-center text-decoration-none gap-2 m-3\"\r\n");
      out.write("						href=\"#\" id=\"userMenuDropdown\" data-bs-toggle=\"dropdown\"\r\n");
      out.write("						aria-expanded=\"false\" aria-haspopup=\"true\"> <img\r\n");
      out.write("						src=\"");
      out.print( session.getAttribute("pfp") );
      out.write("\" \r\n");
      out.write("						class=\"rounded-circle\"\r\n");
      out.write("						style=\"width: 38px; height: 38px; object-fit: cover; border: 1px solid rgba(0, 0, 0, .06);\">\r\n");
      out.write("						<span>");
      out.print( user.getNombre() );
      out.write("</span> <i class=\"bi bi-chevron-down\"></i>\r\n");
      out.write("					</a>\r\n");
      out.write("					<ul class=\"dropdown-menu dropdown-menu-end shadow-sm\"\r\n");
      out.write("						aria-labelledby=\"userMenuDropdown\">\r\n");
      out.write("						<li><a class=\"dropdown-item\" href=\"perfil\">Mi\r\n");
      out.write("								perfil</a></li>\r\n");
      out.write("						<li>\r\n");
      out.write("							<hr class=\"dropdown-divider\">\r\n");
      out.write("						</li>\r\n");
      out.write("						<li><a class=\"dropdown-item text-danger\"\r\n");
      out.write("							href=\"cerrarsesion\"\r\n");
      out.write("							style=\"color: #dc3545 !important;\">Cerrar sesión</a></li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</nav>\r\n");
      out.write("	</header>\r\n");
      out.write("	<script src=\"assets/js/main.js\"></script>\r\n");
      out.write("	\r\n");
      out.write("	");
}

    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
